-- Migration: create attempts table for Supabase persistence
-- Generated by automation; review before applying to production

-- Ensure extensions (adjust as needed for your Postgres/Supabase setup)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Table: public.attempts
CREATE TABLE IF NOT EXISTS public.attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  scenario text NOT NULL,
  workflow_type text NOT NULL,
  payload_json jsonb,
  score numeric,
  completion_state text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS attempts_user_id_idx ON public.attempts (user_id);
CREATE INDEX IF NOT EXISTS attempts_scenario_idx ON public.attempts (scenario);
CREATE INDEX IF NOT EXISTS attempts_created_at_idx ON public.attempts (created_at);

-- Row Level Security scaffold (enable and add example policy)
ALTER TABLE public.attempts ENABLE ROW LEVEL SECURITY;

-- Example policy: allow users to access their own attempts.
-- NOTE: This is a scaffold. Supabase `auth` integration and actual
-- policy expressions should be configured when auth is enforced.
CREATE POLICY "Allow users to access own attempts"
  ON public.attempts
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Keep a trigger to update `updated_at` on row change
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON public.attempts;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.attempts
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_updated_at();

-- End migration
