"use strict";
(async function initNetworkLab(){
 const NS="http://www.w3.org/2000/svg";
 const [tr,symbolLibrary,connectionLibrary]=await Promise.all([fetch("/data/circuit-templates/12v-can-lin-network.json"),window.TorqueMindSymbolLibrary.loadCatalogs("/data/symbols"),window.TorqueMindConnectionLibrary.loadConnectionStyles("/data/connections")]);
 if(!tr.ok)throw new Error("Unable to load network template.");
 const circuit=await tr.json(),engine=window.TorqueMindCircuitEngine;
 const validation=window.TorqueMindCircuitTemplateContracts.validateCircuitTemplate(circuit,engine,symbolLibrary.registry,connectionLibrary.registry);
 if(!validation.valid)throw new Error(validation.errors.join("; "));
 const svg=document.getElementById("circuitSvg"),inspector=document.getElementById("inspectorContent"),stateSelect=document.getElementById("stateSelect"),faultSelect=document.getElementById("faultSelect"),stateBadge=document.getElementById("stateBadge"),flowNote=document.getElementById("flowNote"),voltageProfile=document.getElementById("voltageProfile");
 const vd=window.TorqueMindVoltageDomains.describeVoltageArchitecture(circuit),vmap=new Map(vd.map(d=>[d.id,d]));
 for(const d of vd){const chip=document.createElement("span");chip.className=`voltage-chip voltage-domain-${d.domainClass}`;const small=document.createElement("small");small.textContent=d.powertrainLabel;const val=document.createElement("span");val.textContent=d.label;chip.append(small,val);voltageProfile.append(chip);}
 for(const s of circuit.operatingStates){const o=document.createElement("option");o.value=s.id;o.textContent=s.label;if(s.id==="can-lin-active")o.selected=true;stateSelect.append(o);}
 for(const f of circuit.faultCatalog){const o=document.createElement("option");o.value=f.id;o.textContent=f.label;faultSelect.append(o);}
 const cbid=new Map(circuit.components.map(c=>[c.id,c])),owner=new Map();for(const c of circuit.components)for(const t of c.terminals)owner.set(t.id,c.id);
 let operatingState=stateSelect.value,activeFault="",flowMode="system",selected="";
 const roles={BAT1:"12 V nominal source.",FUSE1:"Generic module-circuit protection.",GW1:"Gateway/controller linking CAN and LIN training networks.",CAN_A:"Generic CAN network node.",CAN_B:"Generic CAN network node.",LIN_A:"Generic LIN sub-node.",GND1:"Common chassis return reference."};
 function el(n,a={},txt=""){const x=document.createElementNS(NS,n);for(const[k,v]of Object.entries(a))x.setAttribute(k,String(v));if(txt)x.textContent=txt;return x;}
 function state(){return circuit.operatingStates.find(s=>s.id===operatingState)} function fault(){return activeFault?engine.getFault(circuit,activeFault):null}
 function pt(id){const oid=owner.get(id),c=cbid.get(oid),p=circuit.layout.positions[oid],td=c.terminals.find(t=>t.id===id),sym=symbolLibrary.registry.get(c.symbolId),st=sym.terminals.find(t=>t.id===td.symbolTerminalId);return{x:p.x-50+st.x,y:p.y-50+st.y};}
 function path(c){const a=pt(c.from),b=pt(c.to);
  if(c.type==="ground_reference"){const y=c.id==="W_BAT_GND"?585:545;return`M ${a.x} ${a.y} V ${y} H ${b.x} V ${b.y}`;}
  if(c.type==="CAN"){const y=c.id.includes("CAN_H")?235:275;return`M ${a.x} ${a.y} V ${y} H ${b.x} V ${b.y}`;}
  if(c.type==="LIN"){return`M ${a.x} ${a.y} H 500 V ${b.y} H ${b.x}`;}
  if(c.id==="W_BAT_FUSE")return`M ${a.x} ${a.y} V 90 H ${b.x}`;
  if(c.id.startsWith("W_FUSE_")){const x=300+["W_FUSE_GW","W_FUSE_CAN_A","W_FUSE_CAN_B","W_FUSE_LIN_A"].indexOf(c.id)*50;return`M ${a.x} ${a.y} H ${x} V ${b.y} H ${b.x}`;}
  const mx=(a.x+b.x)/2;return`M ${a.x} ${a.y} H ${mx} V ${b.y} H ${b.x}`;}
 function defs(){const d=el("defs");for(const[id,color]of[["arrow-power","#c62828"],["arrow-ground","#20252d"],["arrow-can","#405d7a"],["arrow-lin","#6c5a7a"],["arrow-fault","#ef6c00"]]){const m=el("marker",{id,viewBox:"0 0 10 10",refX:"8",refY:"5",markerWidth:7,markerHeight:7,orient:"auto-start-reverse"});m.append(el("path",{d:"M0 0 L10 5 L0 10 z",fill:color}));d.append(m);}svg.append(d);}
 function flows(){const f=state().activeFlows;if(flowMode==="system")return f;return{power:flowMode==="power"?f.power:[],ground:flowMode==="ground"?f.ground:[],can:flowMode==="can"?f.can:[],lin:flowMode==="lin"?f.lin:[]};}
 function fmap(){const m=new Map(),f=flows();for(const k of["power","ground","can","lin"])for(const[id,dir]of f[k]||[])m.set(id,{kind:k,direction:dir});return m;}
 function allowed(id){const f=fault();return!(f&&f.type==="open_circuit"&&f.targetConnectionId===id);}
 function wires(){const fm=fmap(),ft=fault();for(const c of circuit.connections){const fl=fm.get(c.id),style=connectionLibrary.registry.get(c.styleId),domain=vmap.get(c.voltageSystemId),short=ft?.targetConnectionId===c.id&&["short_to_ground","short_to_power","short_between_lines"].includes(ft.type);const p=el("path",{d:path(c),class:["wire",`wire-role-${style.strokeRole}`,`voltage-domain-${domain.domainClass}`,c.type.toLowerCase(),fl&&allowed(c.id)?`flow-${fl.kind}`:"",fl?.direction==="reverse"?"reverse":"",ft?.targetConnectionId===c.id&&ft.type==="open_circuit"?"fault-open":"",short?"fault-short":""].filter(Boolean).join(" "),"data-connection-id":c.id,"data-style-id":c.styleId});if(fl&&allowed(c.id)){const marker=fl.kind==="power"?"arrow-power":fl.kind==="ground"?"arrow-ground":fl.kind==="can"?"arrow-can":"arrow-lin";p.setAttribute(fl.direction==="reverse"?"marker-start":"marker-end",`url(#${marker})`);}svg.append(p);}
  if(ft&&["short_to_ground","short_to_power","short_between_lines"].includes(ft.type)){const a=pt(ft.targetTerminalId),b=pt(ft.shortTargetTerminalId);svg.append(el("path",{d:`M ${a.x} ${a.y} L ${b.x} ${b.y}`,class:"wire fault-short","data-fault-short-id":ft.id}));}}
 function comps(){for(const c of circuit.components){const p=circuit.layout.positions[c.id],g=el("g",{class:["component",selected===c.id?"selected":""].filter(Boolean).join(" "),role:"button",tabindex:"0","data-component-id":c.id});g.append(el("rect",{x:p.x-72,y:p.y-68,width:144,height:144,rx:12,class:"hit-target"}));const s=symbolLibrary.registry.get(c.symbolId);window.TorqueMindSymbolRenderer.renderSymbol(g,s,{x:p.x-50,y:p.y-50,scale:1,className:"component-library-symbol",role:"presentation",ariaLabel:s.name});g.addEventListener("click",()=>inspect(c.id));svg.append(g);}}
 function labels(){for(const c of circuit.components){const l=circuit.labels[c.id],p=circuit.layout.positions[c.id];if(!l)continue;const cx=l.x+l.width/2,cy=l.y+l.height/2,g=el("g",{class:"component-label","aria-hidden":"true"});g.append(el("path",{d:`M ${p.x} ${p.y} L ${cx} ${cy}`,class:"label-leader"}));g.append(el("rect",{x:l.x,y:l.y,width:l.width,height:l.height,rx:8,class:"label-chip"}));g.append(el("text",{x:cx,y:l.y+20,class:"label-title"},l.title));g.append(el("text",{x:cx,y:l.y+38,class:"label-subtitle"},l.subtitle));svg.append(g);}}
 function tps(){for(const tp of circuit.testPoints){const p=pt(tp.terminalId),g=el("g",{class:"test-point",role:"button",tabindex:"0","data-test-point-id":tp.id});g.append(el("circle",{cx:p.x,cy:p.y,r:8}));g.append(el("text",{x:p.x+11,y:p.y-10},"TP"));g.addEventListener("click",()=>inspectTp(tp));svg.append(g);}}
 function render(){svg.querySelectorAll("*:not(title)").forEach(n=>n.remove());defs();wires();comps();labels();tps();stateBadge.textContent=state().label;flowNote.textContent=state().note+" Network animation is conceptual and does not represent measured bus voltage, resistance, or data rate.";}
 function inspect(id){selected=id;const c=cbid.get(id),points=engine.getAvailableTestPoints(circuit,id);inspector.replaceChildren();const h=document.createElement("h3");h.textContent=c.name;const p=document.createElement("p");p.textContent=roles[id];const dl=document.createElement("dl");for(const[l,v]of[["Library symbol",c.symbolId],["Voltage domain",c.voltageSystemId],["Terminals",c.terminals.map(t=>t.name).join(", ")],["Test points",points.length?points.map(x=>x.id).join(", "):"None"]]){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=l;dd.textContent=v;dl.append(dt,dd);}inspector.append(h,p,dl);render();}
 function inspectTp(tp){inspector.replaceChildren();const h=document.createElement("h3"),p=document.createElement("p");h.textContent=tp.id;p.textContent=`Conceptual measurements: ${tp.measurementTypes.join(", ")}. Vehicle-specific values are intentionally omitted.`;inspector.append(h,p);}
 stateSelect.onchange=()=>{operatingState=stateSelect.value;flowMode="system";render()};faultSelect.onchange=()=>{activeFault=faultSelect.value;render()};
 document.getElementById("showSystemFlow").onclick=()=>{flowMode="system";render()};document.getElementById("tracePower").onclick=()=>{flowMode="power";render()};document.getElementById("traceCan").onclick=()=>{flowMode="can";render()};document.getElementById("traceLin").onclick=()=>{flowMode="lin";render()};document.getElementById("traceGround").onclick=()=>{flowMode="ground";render()};document.getElementById("resetView").onclick=()=>{operatingState="can-lin-active";stateSelect.value=operatingState;activeFault="";faultSelect.value="";flowMode="system";selected="";render()};render();
})().catch(e=>{console.error(e);const x=document.getElementById("inspectorContent");if(x)x.textContent="The network template could not be loaded.";});