window.AuthoringTemplates = {
  "no-start": {
    title: "No-start after overnight soak",
    complaint: "Customer states the engine cranks but will not start after sitting overnight.",
    year: "2018",
    make: "Ford",
    model: "F-150",
    engine: "5.0L V8",
    mileage: "84200",
    system: "Engine Performance",
    primaryDtc: "P0335",
    dtcDescription: "Crankshaft Position Sensor Circuit",
    freezeFrame: "RPM 0, ECT 42°F, battery voltage 12.1V during crank.",
    rpm: "0",
    voltage: "12.1",
    coolant: "42°F",
    fuelTrim: "+18%",
    initialTest: "Verify CKP signal while cranking",
    expectedFinding: "No RPM signal during crank",
    rootCause: "Failed crankshaft position sensor",
    recommendedRepair: "Replace crankshaft position sensor, clear codes, and verify restart.",
    aseArea: "A8 Engine Performance",
    safetyCriteria: "Uses safe test procedures.",
    diagnosticCriteria: "Uses evidence to isolate the fault.",
    verificationCriteria: "Confirms restart and no returning DTC."
  },
  "misfire": {
    title: "Cylinder 2 Misfire",
    complaint: "Customer states the MIL is on and the engine runs rough at idle.",
    year: "2019",
    make: "Toyota",
    model: "Camry",
    engine: "2.5L",
    mileage: "61500",
    system: "Engine Performance",
    primaryDtc: "P0302",
    dtcDescription: "Cylinder 2 Misfire Detected",
    freezeFrame: "Idle misfire counter elevated on cylinder 2.",
    rpm: "720",
    voltage: "14.2",
    coolant: "188°F",
    fuelTrim: "+12%",
    initialTest: "Swap cylinder 2 ignition coil with another cylinder",
    expectedFinding: "Misfire follows the ignition coil",
    rootCause: "Failed ignition coil",
    recommendedRepair: "Replace failed ignition coil and verify misfire counter stays at zero.",
    aseArea: "A8 Engine Performance",
    safetyCriteria: "Uses safe ignition testing procedures.",
    diagnosticCriteria: "Confirms misfire source before replacement.",
    verificationCriteria: "Confirms no misfire after repair."
  },
  "charging": {
    title: "Low Charging Voltage",
    complaint: "Customer states the battery warning lamp is on and the vehicle cranks slowly.",
    year: "2017",
    make: "Chevrolet",
    model: "Silverado",
    engine: "5.3L",
    mileage: "93000",
    system: "Electrical",
    primaryDtc: "P0562",
    dtcDescription: "System Voltage Low",
    freezeFrame: "Charging voltage remains below 12V with engine running.",
    rpm: "850",
    voltage: "11.8",
    coolant: "185°F",
    fuelTrim: "+1%",
    initialTest: "Measure charging voltage at battery and alternator output",
    expectedFinding: "Alternator output below specification",
    rootCause: "Alternator failure",
    recommendedRepair: "Replace alternator and verify 13.5–14.8V charging output.",
    aseArea: "A6 Electrical",
    safetyCriteria: "Uses safe battery and charging system procedures.",
    diagnosticCriteria: "Confirms low alternator output.",
    verificationCriteria: "Confirms charging voltage restored."
  }
};
