begin;

create table if not exists public.curriculum_catalog_courses (
  id text primary key,
  code text not null unique check (code ~ '^AUT [0-9]{3}$'),
  title text not null,
  academic_level text not null check (academic_level in ('undergraduate','graduate')),
  classification text not null check (classification in ('Undergraduate','Graduate')),
  degree_program text not null,
  cip_code text not null check (cip_code ~ '^[0-9]{2}\.[0-9]{4}$'),
  category text not null,
  credits text not null,
  prerequisites text not null,
  description text not null,
  status text not null check (status in ('planned','active','retired')),
  url text not null unique,
  canonical_url text not null unique,
  source_file text not null,
  source_basis text not null,
  delivery jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint curriculum_catalog_courses_classification_matches_level check (
    (academic_level = 'undergraduate' and classification = 'Undergraduate')
    or (academic_level = 'graduate' and classification = 'Graduate')
  )
);

create index if not exists idx_curriculum_catalog_courses_level
  on public.curriculum_catalog_courses(academic_level);
create index if not exists idx_curriculum_catalog_courses_code
  on public.curriculum_catalog_courses(code);

comment on table public.curriculum_catalog_courses is
  'Complete academic course catalog. Catalog inclusion is separate from developed curriculum, lesson approval, training approval, and assessment eligibility.';

alter table public.curriculum_catalog_courses enable row level security;
revoke all on table public.curriculum_catalog_courses from public, anon, authenticated;
grant select, insert, update, delete on table public.curriculum_catalog_courses to service_role;

insert into public.curriculum_catalog_courses (
  id, code, title, academic_level, classification, degree_program, cip_code,
  category, credits, prerequisites, description, status, url,
  canonical_url, source_file, source_basis, delivery
)
values
  ('aut-101','AUT 101','Introduction to Automotive Technology','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','None','Introduction to automotive systems, vehicle technologies, diagnostic processes, industry practices, and emerging automotive technologies.','planned','/catalog/course/?course=AUT-101','https://exam.autolearnpro.com/catalog/course/?course=AUT-101','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-105','AUT 105','Automotive Safety and Professional Practices','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','2','None','Automotive shop safety, hazardous materials, environmental practices, tools, equipment, high-voltage safety, documentation, and professional practices.','planned','/catalog/course/?course=AUT-105','https://exam.autolearnpro.com/catalog/course/?course=AUT-105','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-110','AUT 110','Automotive Mathematics','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','None','Mathematical applications used in automotive technology, including measurement, ratios, proportions, algebra, geometry, electrical calculations, torque, power, and diagnostic calculations.','planned','/catalog/course/?course=AUT-110','https://exam.autolearnpro.com/catalog/course/?course=AUT-110','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-115','AUT 115','Automotive Measurement and Instrumentation','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','AUT 110','Precision measurement and instrumentation including calipers, micrometers, dial indicators, pressure measurement, electrical measurement, tolerances, and specifications.','planned','/catalog/course/?course=AUT-115','https://exam.autolearnpro.com/catalog/course/?course=AUT-115','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-120','AUT 120','Automotive Electrical Systems I','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','AUT 110','Fundamentals of automotive electricity, including voltage, current, resistance, circuits, wiring, relays, fuses, grounding, and electrical testing.','planned','/catalog/course/?course=AUT-120','https://exam.autolearnpro.com/catalog/course/?course=AUT-120','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-121','AUT 121','Automotive Electrical Systems I Laboratory','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','1','Concurrent enrollment in AUT 120','Laboratory application of automotive electrical principles through circuit construction, testing, measurement, and diagnosis.','planned','/catalog/course/?course=AUT-121','https://exam.autolearnpro.com/catalog/course/?course=AUT-121','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-130','AUT 130','Engine Systems I','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','AUT 101','Internal-combustion engine construction and operation, including major engine components, lubrication, cooling, and four-stroke operation.','planned','/catalog/course/?course=AUT-130','https://exam.autolearnpro.com/catalog/course/?course=AUT-130','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-131','AUT 131','Engine Systems I Laboratory','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','1','Concurrent enrollment in AUT 130','Engine inspection, measurement, component identification, disassembly, assembly, and service procedures.','planned','/catalog/course/?course=AUT-131','https://exam.autolearnpro.com/catalog/course/?course=AUT-131','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-140','AUT 140','Automotive Brake Systems','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','AUT 120','Hydraulic and electronic braking systems, disc and drum brakes, ABS, brake control systems, inspection, diagnosis, and service.','planned','/catalog/course/?course=AUT-140','https://exam.autolearnpro.com/catalog/course/?course=AUT-140','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-150','AUT 150','Steering, Suspension, and Wheel Alignment','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','AUT 115','Steering and suspension systems, wheel alignment, tire wear, electric power steering, and vehicle stability systems.','planned','/catalog/course/?course=AUT-150','https://exam.autolearnpro.com/catalog/course/?course=AUT-150','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-160','AUT 160','Manual Transmissions and Drivetrain Systems','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','AUT 115','Clutches, manual transmissions, transfer cases, driveshafts, differentials, axles, four-wheel drive, and all-wheel drive.','planned','/catalog/course/?course=AUT-160','https://exam.autolearnpro.com/catalog/course/?course=AUT-160','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-170','AUT 170','Automotive HVAC Systems','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','3','AUT 120','Automotive heating, ventilation, air conditioning, refrigeration cycles, climate controls, electrical controls, and diagnostics.','planned','/catalog/course/?course=AUT-170','https://exam.autolearnpro.com/catalog/course/?course=AUT-170','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-180','AUT 180','Automotive Technical Documentation and Service Information','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Automotive Foundations','2','AUT 101','Interpretation and use of service information, wiring diagrams, technical specifications, diagnostic procedures, and digital technical resources.','planned','/catalog/course/?course=AUT-180','https://exam.autolearnpro.com/catalog/course/?course=AUT-180','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-200','AUT 200','Engine Systems II','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 130','Advanced engine mechanical systems, valve trains, timing systems, cylinder sealing, lubrication, cooling, and mechanical diagnosis.','planned','/catalog/course/?course=AUT-200','https://exam.autolearnpro.com/catalog/course/?course=AUT-200','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-201','AUT 201','Engine Systems II Laboratory','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','1','Concurrent enrollment in AUT 200','Laboratory analysis, measurement, inspection, and diagnosis of engine mechanical systems.','planned','/catalog/course/?course=AUT-201','https://exam.autolearnpro.com/catalog/course/?course=AUT-201','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-210','AUT 210','Engine Performance and Fuel Systems','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 200, AUT 120','Fuel injection, ignition, electronic throttle control, air induction, sensors, actuators, and engine performance systems.','planned','/catalog/course/?course=AUT-210','https://exam.autolearnpro.com/catalog/course/?course=AUT-210','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-211','AUT 211','Engine Performance Laboratory','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','1','Concurrent enrollment in AUT 210','Engine-performance testing using scan tools, meters, oscilloscopes, pressure-testing equipment, and technical specifications.','planned','/catalog/course/?course=AUT-211','https://exam.autolearnpro.com/catalog/course/?course=AUT-211','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-220','AUT 220','Automatic Transmissions and Transaxles','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 160','Automatic transmissions, transaxles, torque converters, planetary gearsets, hydraulic controls, electronic controls, and CVTs.','planned','/catalog/course/?course=AUT-220','https://exam.autolearnpro.com/catalog/course/?course=AUT-220','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-230','AUT 230','Automotive Electronics','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 120, AUT 121','Automotive electronic circuits, semiconductors, sensors, actuators, control modules, signal processing, and electronic diagnostics.','planned','/catalog/course/?course=AUT-230','https://exam.autolearnpro.com/catalog/course/?course=AUT-230','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-240','AUT 240','Automotive Electrical Systems II','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 120, AUT 121','Advanced starting, charging, power distribution, voltage-drop testing, batteries, electrical loads, and electrical diagnostics.','planned','/catalog/course/?course=AUT-240','https://exam.autolearnpro.com/catalog/course/?course=AUT-240','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-250','AUT 250','Automotive Diagnostics I','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 210, AUT 230','Systematic vehicle diagnosis using scan tools, diagnostic trouble codes, live data, testing procedures, specifications, and repair verification.','planned','/catalog/course/?course=AUT-250','https://exam.autolearnpro.com/catalog/course/?course=AUT-250','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-251','AUT 251','Automotive Diagnostics I Laboratory','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','1','Concurrent enrollment in AUT 250','Practical diagnosis of mechanical, electrical, and electronic vehicle faults.','planned','/catalog/course/?course=AUT-251','https://exam.autolearnpro.com/catalog/course/?course=AUT-251','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-260','AUT 260','Vehicle Dynamics','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 110, AUT 150','Forces, torque, acceleration, braking, traction, tire behavior, suspension, steering response, weight transfer, and vehicle stability.','planned','/catalog/course/?course=AUT-260','https://exam.autolearnpro.com/catalog/course/?course=AUT-260','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-270','AUT 270','Automotive Emissions and Environmental Systems','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 210','Vehicle emissions, combustion byproducts, catalytic converters, evaporative systems, oxygen sensors, EGR, and emissions diagnostics.','planned','/catalog/course/?course=AUT-270','https://exam.autolearnpro.com/catalog/course/?course=AUT-270','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-280','AUT 280','Automotive Control Systems','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Core Automotive Systems','3','AUT 230, AUT 250','Electronic control modules, feedback systems, sensors, actuators, control strategies, and computerized vehicle systems.','planned','/catalog/course/?course=AUT-280','https://exam.autolearnpro.com/catalog/course/?course=AUT-280','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-300','AUT 300','Advanced Automotive Diagnostics','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 250, AUT 280','Advanced diagnosis of intermittent, electronic, mechanical, and network-related vehicle faults.','planned','/catalog/course/?course=AUT-300','https://exam.autolearnpro.com/catalog/course/?course=AUT-300','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-301','AUT 301','Advanced Automotive Diagnostics Laboratory','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','1','Concurrent enrollment in AUT 300','Advanced laboratory diagnosis using oscilloscopes, scan tools, network analysis, and vehicle test equipment.','planned','/catalog/course/?course=AUT-301','https://exam.autolearnpro.com/catalog/course/?course=AUT-301','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-310','AUT 310','Vehicle Network Communications','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 230, AUT 280','CAN, CAN FD, LIN, Automotive Ethernet, network architecture, communication messages, network faults, and network diagnostics.','planned','/catalog/course/?course=AUT-310','https://exam.autolearnpro.com/catalog/course/?course=AUT-310','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-320','AUT 320','Hybrid Vehicle Technology','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 240, AUT 280','Hybrid architectures, electric machines, power electronics, regenerative braking, high-voltage systems, battery systems, and diagnostics.','planned','/catalog/course/?course=AUT-320','https://exam.autolearnpro.com/catalog/course/?course=AUT-320','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-321','AUT 321','Hybrid Vehicle Laboratory','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','1','AUT 320','Laboratory analysis and diagnosis of hybrid vehicle systems.','planned','/catalog/course/?course=AUT-321','https://exam.autolearnpro.com/catalog/course/?course=AUT-321','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-330','AUT 330','Electric Vehicle Technology','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 240, AUT 280','Battery-electric vehicle architecture, traction motors, inverters, charging, regenerative braking, thermal management, and diagnostics.','planned','/catalog/course/?course=AUT-330','https://exam.autolearnpro.com/catalog/course/?course=AUT-330','Syllabus - the general foundation o.txt','user-provided academic catalog','{"trainingPackageId":"AUT-250","trainingUrl":"/courses/aut-250/","mappingStatus":"legacy-package-id","note":"Existing approved formative EV training retains its historical package identifier while catalog numbering follows the academic catalog."}'::jsonb),
  ('aut-331','AUT 331','Electric Vehicle Laboratory','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','1','AUT 330','Laboratory analysis of EV electrical, battery, charging, and high-voltage systems.','planned','/catalog/course/?course=AUT-331','https://exam.autolearnpro.com/catalog/course/?course=AUT-331','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-340','AUT 340','Battery Systems and Battery Management','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 330','Battery cells, packs, battery-management systems, state of charge, state of health, thermal management, balancing, degradation, and diagnostics.','planned','/catalog/course/?course=AUT-340','https://exam.autolearnpro.com/catalog/course/?course=AUT-340','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-350','AUT 350','Advanced Driver Assistance Systems','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 280, AUT 310','Camera, radar, ultrasonic, adaptive cruise, lane systems, collision avoidance, sensor calibration, and ADAS diagnostics.','planned','/catalog/course/?course=AUT-350','https://exam.autolearnpro.com/catalog/course/?course=AUT-350','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-360','AUT 360','Automotive Data Acquisition and Analysis','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 110, AUT 300','Collection, processing, visualization, and interpretation of vehicle and diagnostic data.','planned','/catalog/course/?course=AUT-360','https://exam.autolearnpro.com/catalog/course/?course=AUT-360','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-370','AUT 370','Automotive Embedded Systems','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 230, AUT 310','Microcontrollers, embedded systems, ECU architecture, real-time systems, inputs, outputs, and automotive computing.','planned','/catalog/course/?course=AUT-370','https://exam.autolearnpro.com/catalog/course/?course=AUT-370','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-380','AUT 380','Automotive Cybersecurity','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 310, AUT 370','Vehicle cybersecurity, threat modeling, ECU security, secure communication, intrusion detection, and cybersecurity risk management.','planned','/catalog/course/?course=AUT-380','https://exam.autolearnpro.com/catalog/course/?course=AUT-380','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-390','AUT 390','Connected and Software-Defined Vehicles','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 310, AUT 370','Connected vehicles, cloud services, over-the-air updates, centralized computing, software architecture, and vehicle data.','planned','/catalog/course/?course=AUT-390','https://exam.autolearnpro.com/catalog/course/?course=AUT-390','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-400','AUT 400','Automotive Technology Research Methods','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','Junior standing, AUT 300','Research questions, literature reviews, experimental design, data collection, analysis, technical writing, and research presentation.','planned','/catalog/course/?course=AUT-400','https://exam.autolearnpro.com/catalog/course/?course=AUT-400','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-410','AUT 410','Automotive Systems Integration','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 310, AUT 320 or AUT 330, AUT 350','Integration of mechanical, electrical, electronic, software, communication, and energy systems within modern vehicles.','planned','/catalog/course/?course=AUT-410','https://exam.autolearnpro.com/catalog/course/?course=AUT-410','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-420','AUT 420','Automotive Technology Internship','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','Senior standing and department approval','Supervised professional experience in automotive technology, diagnostics, research, manufacturing, fleet operations, or related industry settings.','planned','/catalog/course/?course=AUT-420','https://exam.autolearnpro.com/catalog/course/?course=AUT-420','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-450','AUT 450','Automotive Technology Capstone I','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','2','AUT 400 and senior standing','Development of a comprehensive automotive technology project, including problem definition, research, requirements, methodology, and project planning.','planned','/catalog/course/?course=AUT-450','https://exam.autolearnpro.com/catalog/course/?course=AUT-450','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-451','AUT 451','Automotive Technology Capstone II','undergraduate','Undergraduate','Bachelor of Science in Automotive Technology','47.0604','Advanced Automotive Technology','3','AUT 450','Completion, testing, documentation, and presentation of an applied automotive technology project.','planned','/catalog/course/?course=AUT-451','https://exam.autolearnpro.com/catalog/course/?course=AUT-451','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-501','AUT 501','Advanced Automotive Systems','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','Bachelor''s degree in automotive technology, engineering, applied technology, or related field','Advanced analysis of integrated mechanical, electrical, electronic, software, communication, and energy systems.','planned','/catalog/course/?course=AUT-501','https://exam.autolearnpro.com/catalog/course/?course=AUT-501','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-510','AUT 510','Advanced Vehicle Diagnostics','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 501 or equivalent','Advanced fault isolation, diagnostic reasoning, model-based diagnostics, network faults, waveform analysis, and diagnostic validation.','planned','/catalog/course/?course=AUT-510','https://exam.autolearnpro.com/catalog/course/?course=AUT-510','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-515','AUT 515','Automotive Systems Modeling','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','Graduate-level mathematics or equivalent','Mathematical and computational modeling of vehicle systems, simulation, parameter estimation, and model validation.','planned','/catalog/course/?course=AUT-515','https://exam.autolearnpro.com/catalog/course/?course=AUT-515','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-520','AUT 520','Advanced Vehicle Data Analytics','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 515 or equivalent','Statistical analysis, time-series data, anomaly detection, predictive maintenance, visualization, and interpretation of vehicle datasets.','planned','/catalog/course/?course=AUT-520','https://exam.autolearnpro.com/catalog/course/?course=AUT-520','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-525','AUT 525','Experimental Methods in Automotive Technology','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 501','Experimental design, instrumentation, measurement uncertainty, data acquisition, validation, repeatability, and technical reporting.','planned','/catalog/course/?course=AUT-525','https://exam.autolearnpro.com/catalog/course/?course=AUT-525','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-530','AUT 530','Advanced Electric Vehicle Systems','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 501 and undergraduate EV coursework or equivalent','Advanced EV architectures, electric machines, inverters, charging systems, regenerative braking, thermal systems, and energy management.','planned','/catalog/course/?course=AUT-530','https://exam.autolearnpro.com/catalog/course/?course=AUT-530','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-535','AUT 535','Advanced Battery Systems','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 530','Battery modeling, state estimation, degradation, thermal behavior, balancing, battery-management algorithms, safety, and diagnostics.','planned','/catalog/course/?course=AUT-535','https://exam.autolearnpro.com/catalog/course/?course=AUT-535','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-540','AUT 540','Power Electronics for Vehicle Systems','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 530 or equivalent','Converters, inverters, switching devices, motor drives, control strategies, efficiency, and thermal management.','planned','/catalog/course/?course=AUT-540','https://exam.autolearnpro.com/catalog/course/?course=AUT-540','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-545','AUT 545','Advanced Vehicle Energy Management','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 530, AUT 535','Energy-flow analysis and optimization in hybrid and electric vehicles.','planned','/catalog/course/?course=AUT-545','https://exam.autolearnpro.com/catalog/course/?course=AUT-545','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-550','AUT 550','Advanced Automotive Networks','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 501 or equivalent','Advanced CAN, CAN FD, Automotive Ethernet, gateways, network timing, diagnostics, communication reliability, and network analysis.','planned','/catalog/course/?course=AUT-550','https://exam.autolearnpro.com/catalog/course/?course=AUT-550','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-555','AUT 555','Automotive Embedded Systems and ECU Architecture','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 550 or equivalent','Advanced ECU architecture, microcontrollers, real-time systems, embedded software, communication interfaces, and system validation.','planned','/catalog/course/?course=AUT-555','https://exam.autolearnpro.com/catalog/course/?course=AUT-555','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-560','AUT 560','Advanced ADAS and Vehicle Perception','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 501, AUT 550','Advanced vehicle perception using radar, cameras, LiDAR, sensor fusion, calibration, testing, and validation.','planned','/catalog/course/?course=AUT-560','https://exam.autolearnpro.com/catalog/course/?course=AUT-560','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-565','AUT 565','Autonomous Vehicle Systems','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 560','Autonomous vehicle architecture, localization, mapping, perception, planning, vehicle control, simulation, testing, and validation.','planned','/catalog/course/?course=AUT-565','https://exam.autolearnpro.com/catalog/course/?course=AUT-565','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-570','AUT 570','Automotive Cybersecurity Engineering','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 550','Threat modeling, vehicle attack surfaces, secure networks, authentication, intrusion detection, secure diagnostics, and cybersecurity engineering.','planned','/catalog/course/?course=AUT-570','https://exam.autolearnpro.com/catalog/course/?course=AUT-570','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-575','AUT 575','Software-Defined Vehicle Architecture','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 555, AUT 550','Zonal and centralized architectures, software platforms, middleware, over-the-air updates, vehicle data, and software lifecycle management.','planned','/catalog/course/?course=AUT-575','https://exam.autolearnpro.com/catalog/course/?course=AUT-575','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-580','AUT 580','Advanced Automotive Control Systems','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 515','Advanced feedback control, state-space models, stability, estimation, optimization, and control applications in vehicle systems.','planned','/catalog/course/?course=AUT-580','https://exam.autolearnpro.com/catalog/course/?course=AUT-580','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-585','AUT 585','Vehicle Digital Twins and Simulation','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','3','AUT 515, AUT 520','Digital representations of vehicles, simulation, model calibration, real-time data integration, validation, and predictive analysis.','planned','/catalog/course/?course=AUT-585','https://exam.autolearnpro.com/catalog/course/?course=AUT-585','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-590','AUT 590','Advanced Automotive Technology Seminar','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Core and Specializations','1–3','Graduate standing','Critical examination of current automotive research, technologies, standards, technical publications, and emerging industry developments.','planned','/catalog/course/?course=AUT-590','https://exam.autolearnpro.com/catalog/course/?course=AUT-590','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-600','AUT 600','Automotive Research Design','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Research and Professional Practice','3','AUT 525','Advanced research design, research questions, hypotheses, experimental protocols, analytical methods, validation, and research proposals.','planned','/catalog/course/?course=AUT-600','https://exam.autolearnpro.com/catalog/course/?course=AUT-600','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-610','AUT 610','Applied Automotive Research Project','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Research and Professional Practice','3','AUT 600','Supervised applied research addressing an automotive technology problem through data collection, analysis, evaluation, and technical reporting.','planned','/catalog/course/?course=AUT-610','https://exam.autolearnpro.com/catalog/course/?course=AUT-610','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-620','AUT 620','Graduate Automotive Technology Internship','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Research and Professional Practice','3','Graduate standing and program approval','Advanced professional experience involving automotive research, engineering technology, diagnostics, testing, manufacturing, or vehicle development.','planned','/catalog/course/?course=AUT-620','https://exam.autolearnpro.com/catalog/course/?course=AUT-620','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-630','AUT 630','Advanced Automotive Systems Integration','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Research and Professional Practice','3','AUT 515 and two advanced technology courses','Integration and evaluation of mechanical, electrical, electronic, software, communication, energy, and control systems.','planned','/catalog/course/?course=AUT-630','https://exam.autolearnpro.com/catalog/course/?course=AUT-630','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-640','AUT 640','Automotive Technology Thesis','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Research and Professional Practice','3–6','AUT 600 and thesis-advisor approval','Original graduate research culminating in a master''s thesis and formal defense.','planned','/catalog/course/?course=AUT-640','https://exam.autolearnpro.com/catalog/course/?course=AUT-640','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-650','AUT 650','Applied Automotive Technology Capstone','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Research and Professional Practice','3–6','AUT 600','Advanced applied project involving design, development, testing, evaluation, or integration of an automotive technology solution.','planned','/catalog/course/?course=AUT-650','https://exam.autolearnpro.com/catalog/course/?course=AUT-650','Syllabus - the general foundation o.txt','user-provided academic catalog',null),
  ('aut-690','AUT 690','Graduate Research Seminar','graduate','Graduate','Master of Science in Advanced Automotive Technology','15.0803','Graduate Research and Professional Practice','1','Graduate standing','Graduate presentation and discussion of automotive research, emerging technologies, technical literature, and professional research practices.','planned','/catalog/course/?course=AUT-690','https://exam.autolearnpro.com/catalog/course/?course=AUT-690','Syllabus - the general foundation o.txt','user-provided academic catalog',null)
on conflict (id) do update set
  code = excluded.code,
  title = excluded.title,
  academic_level = excluded.academic_level,
  classification = excluded.classification,
  degree_program = excluded.degree_program,
  cip_code = excluded.cip_code,
  category = excluded.category,
  credits = excluded.credits,
  prerequisites = excluded.prerequisites,
  description = excluded.description,
  status = excluded.status,
  url = excluded.url,
  canonical_url = excluded.canonical_url,
  source_file = excluded.source_file,
  source_basis = excluded.source_basis,
  delivery = excluded.delivery,
  updated_at = now();

commit;
