begin;

insert into public.curriculum_courses (id, program_id, academic_level, cip_code, title, status) values
  ('aut-300','automotive-technology','undergraduate','47.0604','Advanced Automotive Diagnostics','planned'),
  ('aut-301','automotive-technology','undergraduate','47.0604','Advanced Automotive Diagnostics Laboratory','planned'),
  ('aut-310','automotive-technology','undergraduate','47.0604','Vehicle Network Communications','planned'),
  ('aut-320','automotive-technology','undergraduate','47.0604','Hybrid Vehicle Technology','planned'),
  ('aut-321','automotive-technology','undergraduate','47.0604','Hybrid Vehicle Laboratory','planned'),
  ('aut-331','automotive-technology','undergraduate','47.0604','Electric Vehicle Laboratory','planned'),
  ('aut-340','automotive-technology','undergraduate','47.0604','Battery Systems and Battery Management','planned'),
  ('aut-350','automotive-technology','undergraduate','47.0604','Advanced Driver Assistance Systems','planned'),
  ('aut-360','automotive-technology','undergraduate','47.0604','Automotive Data Acquisition and Analysis','planned'),
  ('aut-370','automotive-technology','undergraduate','47.0604','Automotive Embedded Systems','planned'),
  ('aut-380','automotive-technology','undergraduate','47.0604','Automotive Cybersecurity','planned'),
  ('aut-390','automotive-technology','undergraduate','47.0604','Connected and Software-Defined Vehicles','planned')
on conflict (id) do update set program_id=excluded.program_id, academic_level=excluded.academic_level, cip_code=excluded.cip_code, title=excluded.title, status=excluded.status, updated_at=now();

insert into public.curriculum_competencies (id, course_id, academic_level, competency_area_id, statement, status) values
  ('ug-aut300-advanced-diagnostics','aut-300','undergraduate',null,'Integrate multi-domain vehicle evidence, prioritize testable hypotheses, and justify an advanced diagnostic next step using applicable technical information.','planned'),
  ('ug-aut301-advanced-diagnostics-lab','aut-301','undergraduate',null,'Plan and execute generalized advanced diagnostic evidence collection, interpret cross-domain test results, and document a source-supported fault-isolation decision.','planned'),
  ('ug-aut310-network-communications','aut-310','undergraduate',null,'Explain generalized vehicle-network relationships, interpret communication evidence, and use applicable architecture and protocol information to justify a network diagnostic next step.','planned'),
  ('ug-aut320-hybrid-systems','aut-320','undergraduate',null,'Explain generalized hybrid energy-flow and component relationships, recognize high-voltage safety boundaries, and identify applicable information required before diagnostic or service work.','planned'),
  ('ug-aut321-hybrid-lab','aut-321','undergraduate',null,'Organize generalized hybrid laboratory evidence, recognize when work must stop for high-voltage or authorization reasons, and justify an information-supported next diagnostic step.','planned'),
  ('ug-aut331-ev-lab','aut-331','undergraduate',null,'Organize EV laboratory evidence, recognize high-voltage and charging safety boundaries, and justify a safe next diagnostic action using applicable vehicle and equipment information.','planned'),
  ('ug-aut340-battery-management','aut-340','undergraduate',null,'Explain generalized battery and management-system relationships, interpret state and health evidence in context, and identify applicable information required for safe diagnostic decisions.','planned'),
  ('ug-aut350-adas','aut-350','undergraduate',null,'Explain generalized ADAS sensor and control relationships, interpret system evidence, and identify applicable calibration, environmental, and vehicle information required before service decisions.','planned'),
  ('ug-aut360-data-analysis','aut-360','undergraduate',null,'Collect and organize generalized vehicle data, evaluate context and quality, select appropriate visual or analytical representations, and justify conclusions without overstating the evidence.','planned'),
  ('ug-aut370-embedded-systems','aut-370','undergraduate',null,'Explain generalized embedded-system and ECU relationships, trace input-processing-output flow, and distinguish conceptual architecture from implementation-specific details requiring authoritative documentation.','planned'),
  ('ug-aut380-cybersecurity','aut-380','undergraduate',null,'Identify generalized automotive cybersecurity assets, threats, and controls, interpret defensive evidence, and document risk and mitigation reasoning within authorized and ethical boundaries.','planned'),
  ('ug-aut390-connected-sdv','aut-390','undergraduate',null,'Explain generalized connected and software-defined vehicle relationships, identify data and software lifecycle dependencies, and distinguish architectural concepts from implementation-specific claims requiring authoritative information.','planned')
on conflict (id) do update set course_id=excluded.course_id, academic_level=excluded.academic_level, competency_area_id=excluded.competency_area_id, statement=excluded.statement, status=excluded.status, updated_at=now();

insert into public.curriculum_lesson_plans (id, course_id, competency_id, academic_level, title, status) values
  ('ug-aut300-advanced-diagnostics','aut-300','ug-aut300-advanced-diagnostics','undergraduate','Advanced Automotive Diagnostic Strategy and Evidence','planned'),
  ('ug-aut301-advanced-diagnostics-lab','aut-301','ug-aut301-advanced-diagnostics-lab','undergraduate','Advanced Diagnostic Laboratory Testing and Fault Isolation','planned'),
  ('ug-aut310-network-communications','aut-310','ug-aut310-network-communications','undergraduate','Vehicle Network Communications and Diagnostic Evidence','planned'),
  ('ug-aut320-hybrid-vehicle-technology','aut-320','ug-aut320-hybrid-systems','undergraduate','Hybrid Vehicle Architecture, Energy Flow, and Diagnostic Foundations','planned'),
  ('ug-aut321-hybrid-lab','aut-321','ug-aut321-hybrid-lab','undergraduate','Hybrid Vehicle Laboratory Analysis and Evidence','planned'),
  ('ug-aut331-electric-vehicle-lab','aut-331','ug-aut331-ev-lab','undergraduate','Electric Vehicle Laboratory Analysis and High-Voltage Evidence','planned'),
  ('ug-aut340-battery-management','aut-340','ug-aut340-battery-management','undergraduate','Battery Systems, Management, Health, and Diagnostic Evidence','planned'),
  ('ug-aut350-adas','aut-350','ug-aut350-adas','undergraduate','ADAS Sensors, Functions, Calibration Context, and Diagnostic Evidence','planned'),
  ('ug-aut360-data-analysis','aut-360','ug-aut360-data-analysis','undergraduate','Vehicle Data Acquisition, Visualization, and Interpretation','planned'),
  ('ug-aut370-embedded-systems','aut-370','ug-aut370-embedded-systems','undergraduate','Automotive Embedded Systems and ECU Architecture Foundations','planned'),
  ('ug-aut380-cybersecurity','aut-380','ug-aut380-cybersecurity','undergraduate','Automotive Cybersecurity, Threat Modeling, and Risk Foundations','planned'),
  ('ug-aut390-connected-sdv','aut-390','ug-aut390-connected-sdv','undergraduate','Connected and Software-Defined Vehicle Architecture Foundations','planned')
on conflict (id) do update set course_id=excluded.course_id, competency_id=excluded.competency_id, academic_level=excluded.academic_level, title=excluded.title, status=excluded.status, updated_at=now();

insert into public.curriculum_lesson_steps (lesson_plan_id, position, step_text) values
  ('ug-aut300-advanced-diagnostics',1,'Define the advanced concern'),
  ('ug-aut300-advanced-diagnostics',2,'Separate affected domains'),
  ('ug-aut300-advanced-diagnostics',3,'Organize available evidence'),
  ('ug-aut300-advanced-diagnostics',4,'Rank testable hypotheses'),
  ('ug-aut300-advanced-diagnostics',5,'Select a discriminating test'),
  ('ug-aut300-advanced-diagnostics',6,'Interpret results with applicable information'),
  ('ug-aut300-advanced-diagnostics',7,'Plan verification of the conclusion'),
  ('ug-aut300-advanced-diagnostics',8,'Document the evidence chain'),
  ('ug-aut301-advanced-diagnostics-lab',1,'Define the laboratory fault'),
  ('ug-aut301-advanced-diagnostics-lab',2,'Choose the diagnostic domain'),
  ('ug-aut301-advanced-diagnostics-lab',3,'Select appropriate test equipment'),
  ('ug-aut301-advanced-diagnostics-lab',4,'Establish test context'),
  ('ug-aut301-advanced-diagnostics-lab',5,'Collect and compare evidence'),
  ('ug-aut301-advanced-diagnostics-lab',6,'Narrow the fault using applicable information'),
  ('ug-aut301-advanced-diagnostics-lab',7,'Practice verification of the diagnosis'),
  ('ug-aut301-advanced-diagnostics-lab',8,'Document the reasoning and result'),
  ('ug-aut310-network-communications',1,'Identify the communication concern'),
  ('ug-aut310-network-communications',2,'Map the generalized network architecture'),
  ('ug-aut310-network-communications',3,'Identify relevant message paths'),
  ('ug-aut310-network-communications',4,'Classify communication evidence'),
  ('ug-aut310-network-communications',5,'Differentiate node link and message hypotheses'),
  ('ug-aut310-network-communications',6,'Check applicable topology and protocol information'),
  ('ug-aut310-network-communications',7,'Practice a network fault decision'),
  ('ug-aut310-network-communications',8,'Document the supported next step'),
  ('ug-aut320-hybrid-vehicle-technology',1,'Identify the hybrid architecture'),
  ('ug-aut320-hybrid-vehicle-technology',2,'Trace generalized energy flow'),
  ('ug-aut320-hybrid-vehicle-technology',3,'Connect electric-machine roles'),
  ('ug-aut320-hybrid-vehicle-technology',4,'Connect power-electronic functions'),
  ('ug-aut320-hybrid-vehicle-technology',5,'Relate regenerative braking and battery behavior'),
  ('ug-aut320-hybrid-vehicle-technology',6,'Recognize high-voltage information boundaries'),
  ('ug-aut320-hybrid-vehicle-technology',7,'Practice a hybrid diagnostic reasoning scenario'),
  ('ug-aut320-hybrid-vehicle-technology',8,'Document the safe next step'),
  ('ug-aut321-hybrid-lab',1,'Define the hybrid lab objective'),
  ('ug-aut321-hybrid-lab',2,'Identify the affected subsystem'),
  ('ug-aut321-hybrid-lab',3,'Review safety and authorization boundaries'),
  ('ug-aut321-hybrid-lab',4,'Select a generalized evidence approach'),
  ('ug-aut321-hybrid-lab',5,'Record system observations'),
  ('ug-aut321-hybrid-lab',6,'Check applicable technical information'),
  ('ug-aut321-hybrid-lab',7,'Practice a stop/proceed diagnostic decision'),
  ('ug-aut321-hybrid-lab',8,'Document findings and verification needs'),
  ('ug-aut331-electric-vehicle-lab',1,'Define the EV lab objective'),
  ('ug-aut331-electric-vehicle-lab',2,'Identify the electrical or energy subsystem'),
  ('ug-aut331-electric-vehicle-lab',3,'Review high-voltage and charging boundaries'),
  ('ug-aut331-electric-vehicle-lab',4,'Select an evidence-gathering approach'),
  ('ug-aut331-electric-vehicle-lab',5,'Record observations and test context'),
  ('ug-aut331-electric-vehicle-lab',6,'Check applicable vehicle/equipment information'),
  ('ug-aut331-electric-vehicle-lab',7,'Practice a safe diagnostic decision'),
  ('ug-aut331-electric-vehicle-lab',8,'Document findings and verification'),
  ('ug-aut340-battery-management',1,'Identify the battery-system concern'),
  ('ug-aut340-battery-management',2,'Map cell pack and management roles'),
  ('ug-aut340-battery-management',3,'Relate state-of-charge evidence'),
  ('ug-aut340-battery-management',4,'Relate state-of-health evidence'),
  ('ug-aut340-battery-management',5,'Connect thermal and balancing functions'),
  ('ug-aut340-battery-management',6,'Separate generalized trends from vehicle-specific limits'),
  ('ug-aut340-battery-management',7,'Practice a battery diagnostic decision'),
  ('ug-aut340-battery-management',8,'Document the evidence and next step'),
  ('ug-aut350-adas',1,'Define the ADAS concern'),
  ('ug-aut350-adas',2,'Identify the sensing/control function'),
  ('ug-aut350-adas',3,'Map sensor and network relationships'),
  ('ug-aut350-adas',4,'Record relevant environmental/system evidence'),
  ('ug-aut350-adas',5,'Distinguish fault evidence from calibration need'),
  ('ug-aut350-adas',6,'Check applicable calibration/service information'),
  ('ug-aut350-adas',7,'Practice an ADAS diagnostic decision'),
  ('ug-aut350-adas',8,'Document verification requirements'),
  ('ug-aut360-data-analysis',1,'Define the data question'),
  ('ug-aut360-data-analysis',2,'Identify variables and units'),
  ('ug-aut360-data-analysis',3,'Establish collection context'),
  ('ug-aut360-data-analysis',4,'Inspect data quality'),
  ('ug-aut360-data-analysis',5,'Organize and visualize the data'),
  ('ug-aut360-data-analysis',6,'Compare patterns without overclaiming'),
  ('ug-aut360-data-analysis',7,'Practice an evidence-based interpretation'),
  ('ug-aut360-data-analysis',8,'Document assumptions and conclusion'),
  ('ug-aut370-embedded-systems',1,'Identify the embedded function'),
  ('ug-aut370-embedded-systems',2,'Map inputs processing and outputs'),
  ('ug-aut370-embedded-systems',3,'Connect microcontroller and ECU roles'),
  ('ug-aut370-embedded-systems',4,'Consider real-time constraints conceptually'),
  ('ug-aut370-embedded-systems',5,'Relate network and local signals'),
  ('ug-aut370-embedded-systems',6,'Identify implementation-specific information needs'),
  ('ug-aut370-embedded-systems',7,'Practice an embedded-system reasoning scenario'),
  ('ug-aut370-embedded-systems',8,'Document the supported architecture conclusion'),
  ('ug-aut380-cybersecurity',1,'Define the protected vehicle function'),
  ('ug-aut380-cybersecurity',2,'Identify assets and trust boundaries'),
  ('ug-aut380-cybersecurity',3,'Describe plausible threat categories'),
  ('ug-aut380-cybersecurity',4,'Relate preventive and detective controls'),
  ('ug-aut380-cybersecurity',5,'Interpret generalized security evidence'),
  ('ug-aut380-cybersecurity',6,'Assess risk without exploit execution'),
  ('ug-aut380-cybersecurity',7,'Practice a defensive response decision'),
  ('ug-aut380-cybersecurity',8,'Document mitigation and verification needs'),
  ('ug-aut390-connected-sdv',1,'Identify the connected vehicle function'),
  ('ug-aut390-connected-sdv',2,'Map vehicle edge and cloud relationships'),
  ('ug-aut390-connected-sdv',3,'Trace data and service dependencies'),
  ('ug-aut390-connected-sdv',4,'Connect centralized computing concepts'),
  ('ug-aut390-connected-sdv',5,'Describe update/lifecycle relationships'),
  ('ug-aut390-connected-sdv',6,'Identify security and provenance dependencies'),
  ('ug-aut390-connected-sdv',7,'Practice an architecture reasoning scenario'),
  ('ug-aut390-connected-sdv',8,'Document assumptions and source needs')
on conflict (lesson_plan_id, position) do update set step_text=excluded.step_text;

commit;
