begin;

insert into public.curriculum_courses (id, program_id, academic_level, cip_code, title, status) values
  ('aut-200','automotive-technology','undergraduate','47.0604','Engine Systems II','planned'),
  ('aut-201','automotive-technology','undergraduate','47.0604','Engine Systems II Laboratory','planned'),
  ('aut-211','automotive-technology','undergraduate','47.0604','Engine Performance Laboratory','planned'),
  ('aut-220','automotive-technology','undergraduate','47.0604','Automatic Transmissions and Transaxles','planned'),
  ('aut-230','automotive-technology','undergraduate','47.0604','Automotive Electronics','planned'),
  ('aut-240','automotive-technology','undergraduate','47.0604','Automotive Electrical Systems II','planned'),
  ('aut-250','automotive-technology','undergraduate','47.0604','Automotive Diagnostics I','planned'),
  ('aut-251','automotive-technology','undergraduate','47.0604','Automotive Diagnostics I Laboratory','planned'),
  ('aut-260','automotive-technology','undergraduate','47.0604','Vehicle Dynamics','planned'),
  ('aut-270','automotive-technology','undergraduate','47.0604','Automotive Emissions and Environmental Systems','planned'),
  ('aut-280','automotive-technology','undergraduate','47.0604','Automotive Control Systems','planned')
on conflict (id) do update set program_id=excluded.program_id, academic_level=excluded.academic_level, cip_code=excluded.cip_code, title=excluded.title, status=excluded.status, updated_at=now();

insert into public.curriculum_competencies (id, course_id, academic_level, competency_area_id, statement, status) values
  ('ug-aut200-engine-mechanical-diagnosis','aut-200','undergraduate',null,'Analyze advanced engine mechanical relationships, distinguish measured evidence from diagnosis, and identify the applicable service information required before specifications or procedures are used.','planned'),
  ('ug-aut201-engine-mechanical-lab','aut-201','undergraduate',null,'Organize engine mechanical laboratory evidence, select an appropriate measurement or inspection approach, and justify a next step using applicable specifications and documented observations.','planned'),
  ('ug-aut211-engine-performance-lab','aut-211','undergraduate',null,'Collect and interpret generalized engine-performance test evidence, preserve test context and units, and justify a diagnostic next step using applicable technical information.','planned'),
  ('ug-aut220-automatic-transmission-systems','aut-220','undergraduate',null,'Explain generalized automatic-transmission power-flow and control relationships, distinguish system evidence from conclusions, and identify applicable information required for diagnosis or service.','planned'),
  ('ug-aut230-automotive-electronics','aut-230','undergraduate',null,'Explain electronic signal and control relationships, interpret generalized sensor/actuator evidence, and use applicable technical information to justify a diagnostic next step.','planned'),
  ('ug-aut240-advanced-electrical-diagnosis','aut-240','undergraduate',null,'Analyze advanced electrical-system relationships, interpret measurements in operating context, and justify a next diagnostic action using applicable vehicle-specific information.','planned'),
  ('ug-aut250-systematic-diagnostics','aut-250','undergraduate',null,'Organize diagnostic evidence from symptoms, scan data, trouble codes, tests, and applicable information to justify and verify a systematic next diagnostic step.','planned'),
  ('ug-aut251-diagnostics-lab','aut-251','undergraduate',null,'Plan and document generalized fault-isolation work, collect relevant evidence, and justify a safe next test without substituting assumptions for verified vehicle information.','planned'),
  ('ug-aut260-vehicle-dynamics','aut-260','undergraduate',null,'Explain generalized vehicle-dynamics relationships, apply appropriate quantitative reasoning, and distinguish modeled behavior from vehicle-specific limits or measured evidence.','planned'),
  ('ug-aut270-emissions-systems','aut-270','undergraduate',null,'Explain emissions-system relationships, interpret generalized sensor and system evidence, and identify applicable technical or regulatory information required before diagnostic conclusions are made.','planned'),
  ('ug-aut280-control-systems','aut-280','undergraduate',null,'Explain generalized feedback and control relationships, interpret sensor/actuator evidence, and use applicable system information to justify a control-system diagnostic next step.','planned')
on conflict (id) do update set course_id=excluded.course_id, academic_level=excluded.academic_level, competency_area_id=excluded.competency_area_id, statement=excluded.statement, status=excluded.status, updated_at=now();

insert into public.curriculum_lesson_plans (id, course_id, competency_id, academic_level, title, status) values
  ('ug-aut200-engine-systems-ii','aut-200','ug-aut200-engine-mechanical-diagnosis','undergraduate','Advanced Engine Mechanical Systems and Diagnostic Evidence','planned'),
  ('ug-aut201-engine-systems-ii-lab','aut-201','ug-aut201-engine-mechanical-lab','undergraduate','Engine Mechanical Laboratory Analysis and Measurement','planned'),
  ('ug-aut211-engine-performance-lab','aut-211','ug-aut211-engine-performance-lab','undergraduate','Engine Performance Laboratory Testing and Evidence','planned'),
  ('ug-aut220-automatic-transmissions','aut-220','ug-aut220-automatic-transmission-systems','undergraduate','Automatic Transmission and Transaxle System Relationships','planned'),
  ('ug-aut230-automotive-electronics','aut-230','ug-aut230-automotive-electronics','undergraduate','Automotive Electronic Circuits, Signals, and Control Evidence','planned'),
  ('ug-aut240-electrical-systems-ii','aut-240','ug-aut240-advanced-electrical-diagnosis','undergraduate','Advanced Electrical Systems and Diagnostic Evidence','planned'),
  ('ug-aut250-automotive-diagnostics-i','aut-250','ug-aut250-systematic-diagnostics','undergraduate','Systematic Automotive Diagnosis and Verification','planned'),
  ('ug-aut251-diagnostics-lab','aut-251','ug-aut251-diagnostics-lab','undergraduate','Automotive Diagnostics Laboratory Evidence and Fault Isolation','planned'),
  ('ug-aut260-vehicle-dynamics','aut-260','ug-aut260-vehicle-dynamics','undergraduate','Vehicle Dynamics, Forces, and Stability Relationships','planned'),
  ('ug-aut270-emissions-systems','aut-270','ug-aut270-emissions-systems','undergraduate','Automotive Emissions, Aftertreatment, and Diagnostic Evidence','planned'),
  ('ug-aut280-control-systems','aut-280','ug-aut280-control-systems','undergraduate','Automotive Feedback, Control Modules, Sensors, and Actuators','planned')
on conflict (id) do update set course_id=excluded.course_id, competency_id=excluded.competency_id, academic_level=excluded.academic_level, title=excluded.title, status=excluded.status, updated_at=now();

insert into public.curriculum_lesson_steps (lesson_plan_id, position, step_text) values
  ('ug-aut200-engine-systems-ii',1,'Define the mechanical concern'),
  ('ug-aut200-engine-systems-ii',2,'Map the relevant engine subsystem'),
  ('ug-aut200-engine-systems-ii',3,'Identify possible mechanical relationships'),
  ('ug-aut200-engine-systems-ii',4,'Select an evidence-gathering approach'),
  ('ug-aut200-engine-systems-ii',5,'Record observations and measurements'),
  ('ug-aut200-engine-systems-ii',6,'Compare only with applicable specifications'),
  ('ug-aut200-engine-systems-ii',7,'Practice a mechanical diagnostic decision'),
  ('ug-aut200-engine-systems-ii',8,'Document the supported next step'),
  ('ug-aut201-engine-systems-ii-lab',1,'Define the lab objective'),
  ('ug-aut201-engine-systems-ii-lab',2,'Identify the component or subsystem'),
  ('ug-aut201-engine-systems-ii-lab',3,'Select the inspection or measurement approach'),
  ('ug-aut201-engine-systems-ii-lab',4,'Collect condition evidence'),
  ('ug-aut201-engine-systems-ii-lab',5,'Record units and operating context'),
  ('ug-aut201-engine-systems-ii-lab',6,'Verify applicable specifications'),
  ('ug-aut201-engine-systems-ii-lab',7,'Practice an evidence-to-diagnosis decision'),
  ('ug-aut201-engine-systems-ii-lab',8,'Document findings and next action'),
  ('ug-aut211-engine-performance-lab',1,'Define the performance concern'),
  ('ug-aut211-engine-performance-lab',2,'Select the test method'),
  ('ug-aut211-engine-performance-lab',3,'Establish the measurement context'),
  ('ug-aut211-engine-performance-lab',4,'Collect scan or instrument evidence'),
  ('ug-aut211-engine-performance-lab',5,'Record units and operating conditions'),
  ('ug-aut211-engine-performance-lab',6,'Compare with applicable technical information'),
  ('ug-aut211-engine-performance-lab',7,'Practice a performance diagnostic decision'),
  ('ug-aut211-engine-performance-lab',8,'Document the evidence and next step'),
  ('ug-aut220-automatic-transmissions',1,'Identify the transmission configuration'),
  ('ug-aut220-automatic-transmissions',2,'Trace generalized power flow'),
  ('ug-aut220-automatic-transmissions',3,'Connect torque-converter functions'),
  ('ug-aut220-automatic-transmissions',4,'Connect planetary gearset relationships'),
  ('ug-aut220-automatic-transmissions',5,'Relate hydraulic and electronic controls'),
  ('ug-aut220-automatic-transmissions',6,'Classify symptom and control evidence'),
  ('ug-aut220-automatic-transmissions',7,'Practice a transmission reasoning scenario'),
  ('ug-aut220-automatic-transmissions',8,'Document the next diagnostic question'),
  ('ug-aut230-automotive-electronics',1,'Identify the electronic function'),
  ('ug-aut230-automotive-electronics',2,'Map the circuit or signal path'),
  ('ug-aut230-automotive-electronics',3,'Connect semiconductor and control roles'),
  ('ug-aut230-automotive-electronics',4,'Identify sensor and actuator relationships'),
  ('ug-aut230-automotive-electronics',5,'Collect or interpret signal evidence'),
  ('ug-aut230-automotive-electronics',6,'Check applicable technical information'),
  ('ug-aut230-automotive-electronics',7,'Practice an electronic diagnostic decision'),
  ('ug-aut230-automotive-electronics',8,'Document the evidence and next step'),
  ('ug-aut240-electrical-systems-ii',1,'Define the electrical concern'),
  ('ug-aut240-electrical-systems-ii',2,'Map the affected circuit or subsystem'),
  ('ug-aut240-electrical-systems-ii',3,'Identify relevant loads and paths'),
  ('ug-aut240-electrical-systems-ii',4,'Select the electrical test approach'),
  ('ug-aut240-electrical-systems-ii',5,'Record measurements and operating context'),
  ('ug-aut240-electrical-systems-ii',6,'Compare with applicable specifications'),
  ('ug-aut240-electrical-systems-ii',7,'Practice an advanced electrical decision'),
  ('ug-aut240-electrical-systems-ii',8,'Document verification and next action'),
  ('ug-aut250-automotive-diagnostics-i',1,'Confirm and define the concern'),
  ('ug-aut250-automotive-diagnostics-i',2,'Collect initial diagnostic information'),
  ('ug-aut250-automotive-diagnostics-i',3,'Interpret codes and live-data context'),
  ('ug-aut250-automotive-diagnostics-i',4,'Form testable hypotheses'),
  ('ug-aut250-automotive-diagnostics-i',5,'Select an applicable test'),
  ('ug-aut250-automotive-diagnostics-i',6,'Compare evidence with authoritative information'),
  ('ug-aut250-automotive-diagnostics-i',7,'Practice a diagnostic decision and verification plan'),
  ('ug-aut250-automotive-diagnostics-i',8,'Document the evidence chain and next step'),
  ('ug-aut251-diagnostics-lab',1,'Define the laboratory fault or concern'),
  ('ug-aut251-diagnostics-lab',2,'Classify the affected domain'),
  ('ug-aut251-diagnostics-lab',3,'Select a safe evidence-gathering approach'),
  ('ug-aut251-diagnostics-lab',4,'Collect mechanical/electrical/electronic evidence'),
  ('ug-aut251-diagnostics-lab',5,'Record context and observations'),
  ('ug-aut251-diagnostics-lab',6,'Use applicable information to narrow the fault'),
  ('ug-aut251-diagnostics-lab',7,'Practice a fault-isolation decision'),
  ('ug-aut251-diagnostics-lab',8,'Document findings and verification'),
  ('ug-aut260-vehicle-dynamics',1,'Define the dynamic condition'),
  ('ug-aut260-vehicle-dynamics',2,'Identify forces and moments conceptually'),
  ('ug-aut260-vehicle-dynamics',3,'Connect tire and traction behavior'),
  ('ug-aut260-vehicle-dynamics',4,'Relate suspension and steering response'),
  ('ug-aut260-vehicle-dynamics',5,'Consider acceleration braking and weight transfer'),
  ('ug-aut260-vehicle-dynamics',6,'Separate model assumptions from measured evidence'),
  ('ug-aut260-vehicle-dynamics',7,'Practice a dynamics reasoning problem'),
  ('ug-aut260-vehicle-dynamics',8,'Document assumptions and supported conclusions'),
  ('ug-aut270-emissions-systems',1,'Define the emissions-related concern'),
  ('ug-aut270-emissions-systems',2,'Map the relevant emissions subsystem'),
  ('ug-aut270-emissions-systems',3,'Connect combustion and aftertreatment roles'),
  ('ug-aut270-emissions-systems',4,'Relate sensors and control strategies'),
  ('ug-aut270-emissions-systems',5,'Collect or interpret system evidence'),
  ('ug-aut270-emissions-systems',6,'Check applicable technical and regulatory information'),
  ('ug-aut270-emissions-systems',7,'Practice an emissions diagnostic decision'),
  ('ug-aut270-emissions-systems',8,'Document the evidence and next step'),
  ('ug-aut280-control-systems',1,'Define the controlled function'),
  ('ug-aut280-control-systems',2,'Identify inputs outputs and controller'),
  ('ug-aut280-control-systems',3,'Map the feedback relationship'),
  ('ug-aut280-control-systems',4,'Relate sensors and actuators'),
  ('ug-aut280-control-systems',5,'Interpret generalized control evidence'),
  ('ug-aut280-control-systems',6,'Check applicable control information'),
  ('ug-aut280-control-systems',7,'Practice a feedback-system diagnostic decision'),
  ('ug-aut280-control-systems',8,'Document the evidence and next step')
on conflict (lesson_plan_id, position) do update set step_text=excluded.step_text;

commit;
