begin;

insert into public.curriculum_courses (id, program_id, academic_level, cip_code, title, status) values
  ('aut-140','automotive-technology','undergraduate','47.0604','Automotive Brake Systems','planned'),
  ('aut-510','automotive-engineering-technology','graduate','15.0803','Advanced Vehicle Diagnostics','planned'),
  ('aut-600','automotive-engineering-technology','graduate','15.0803','Automotive Research Design','planned'),
  ('aut-610','automotive-engineering-technology','graduate','15.0803','Applied Automotive Research Project','planned'),
  ('aut-620','automotive-engineering-technology','graduate','15.0803','Graduate Automotive Technology Internship','planned'),
  ('aut-630','automotive-engineering-technology','graduate','15.0803','Advanced Automotive Systems Integration','planned'),
  ('aut-640','automotive-engineering-technology','graduate','15.0803','Automotive Technology Thesis','planned'),
  ('aut-650','automotive-engineering-technology','graduate','15.0803','Applied Automotive Technology Capstone','planned'),
  ('aut-690','automotive-engineering-technology','graduate','15.0803','Graduate Research Seminar','planned')
on conflict (id) do update set program_id=excluded.program_id, academic_level=excluded.academic_level, cip_code=excluded.cip_code, title=excluded.title, status=excluded.status, updated_at=now();

insert into public.curriculum_competencies (id, course_id, academic_level, competency_area_id, statement, status) values
  ('ug-aut140-brake-systems','aut-140','undergraduate',null,'Analyze hydraulic and electronic brake-system operation, inspection findings, measurements, ABS/control evidence, and applicable service information to justify a safe diagnostic or service decision.','planned'),
  ('grad-aut510-advanced-vehicle-diagnostics','aut-510','graduate',null,'Integrate model-based, network, waveform, data, and fault-isolation evidence to evaluate competing diagnostic hypotheses and validate technically defensible conclusions.','planned'),
  ('grad-aut600-research-design','aut-600','graduate',null,'Design automotive research using focused questions, hypotheses, experimental protocols, analytical methods, uncertainty controls, validation strategies, and proposal-quality technical communication.','planned'),
  ('grad-aut610-applied-research-project','aut-610','graduate',null,'Execute and evaluate an applied automotive research project through controlled data collection, analysis, validation, technical reporting, and explicit treatment of limitations and provenance.','planned'),
  ('grad-aut620-internship','aut-620','graduate',null,'Document and critically evaluate advanced automotive professional practice using approved objectives, evidence, reflection, technical communication, and explicit institutional supervision boundaries.','planned'),
  ('grad-aut630-systems-integration','aut-630','graduate',null,'Analyze and evaluate integrated mechanical, electrical, electronic, software, communication, energy, and control-system interfaces using systems-engineering and verification evidence.','planned'),
  ('grad-aut640-thesis','aut-640','graduate',null,'Conduct and defend original automotive technology research using approved scholarly methods, transparent provenance, rigorous analysis, uncertainty treatment, and thesis-quality technical communication.','planned'),
  ('grad-aut650-capstone','aut-650','graduate',null,'Plan, develop, test, evaluate, and communicate an advanced automotive technology solution using systems reasoning, measurable requirements, validation evidence, and documented limitations.','planned'),
  ('grad-aut690-research-seminar','aut-690','graduate',null,'Critically evaluate and communicate current automotive research and emerging technology literature using transparent source provenance, methodological critique, uncertainty, and professional scholarly discussion.','planned')
on conflict (id) do update set course_id=excluded.course_id, academic_level=excluded.academic_level, competency_area_id=excluded.competency_area_id, statement=excluded.statement, status=excluded.status, updated_at=now();

insert into public.curriculum_lesson_plans (id, course_id, competency_id, academic_level, title, status) values
  ('ug-aut140-brake-systems','aut-140','ug-aut140-brake-systems','undergraduate','Automotive Brake Systems, ABS, and Diagnostic Evidence','planned'),
  ('grad-aut510-advanced-vehicle-diagnostics','aut-510','grad-aut510-advanced-vehicle-diagnostics','graduate','Advanced Vehicle Diagnostic Reasoning, Fault Isolation, and Validation','planned'),
  ('grad-aut600-research-design','aut-600','grad-aut600-research-design','graduate','Automotive Research Design, Protocols, Analysis, and Validation','planned'),
  ('grad-aut610-applied-research-project','aut-610','grad-aut610-applied-research-project','graduate','Applied Automotive Research Execution, Analysis, and Reporting','planned'),
  ('grad-aut620-internship','aut-620','grad-aut620-internship','graduate','Graduate Automotive Internship Evidence, Professional Practice, and Reflection','planned'),
  ('grad-aut630-systems-integration','aut-630','grad-aut630-systems-integration','graduate','Advanced Automotive Systems Integration, Interfaces, and Verification','planned'),
  ('grad-aut640-thesis','aut-640','grad-aut640-thesis','graduate','Automotive Thesis Research, Validation, Documentation, and Defense','planned'),
  ('grad-aut650-capstone','aut-650','grad-aut650-capstone','graduate','Applied Automotive Technology Capstone Design, Test, and Evaluation','planned'),
  ('grad-aut690-research-seminar','aut-690','grad-aut690-research-seminar','graduate','Graduate Automotive Research Seminar, Literature Critique, and Scholarly Communication','planned')
on conflict (id) do update set course_id=excluded.course_id, competency_id=excluded.competency_id, academic_level=excluded.academic_level, title=excluded.title, status=excluded.status, updated_at=now();

delete from public.curriculum_lesson_steps where lesson_plan_id in ('ug-aut140-brake-systems','grad-aut510-advanced-vehicle-diagnostics','grad-aut600-research-design','grad-aut610-applied-research-project','grad-aut620-internship','grad-aut630-systems-integration','grad-aut640-thesis','grad-aut650-capstone','grad-aut690-research-seminar');

insert into public.curriculum_lesson_steps (lesson_plan_id, position, step_text) values
  ('ug-aut140-brake-systems',1,'Establish brake-system safety and service-information boundaries'),
  ('ug-aut140-brake-systems',2,'Map hydraulic friction and electronic brake-control relationships'),
  ('ug-aut140-brake-systems',3,'Distinguish disc drum parking and assist-system roles'),
  ('ug-aut140-brake-systems',4,'Interpret inspection wear and hydraulic-condition evidence'),
  ('ug-aut140-brake-systems',5,'Relate wheel-speed ABS and stability-control inputs'),
  ('ug-aut140-brake-systems',6,'Compare measurements with applicable specifications'),
  ('ug-aut140-brake-systems',7,'Form and test brake-system hypotheses'),
  ('ug-aut140-brake-systems',8,'Document the supported repair or diagnostic next step'),
  ('grad-aut510-advanced-vehicle-diagnostics',1,'Define the advanced diagnostic problem and evidence boundary'),
  ('grad-aut510-advanced-vehicle-diagnostics',2,'Model the relevant vehicle system and failure pathways'),
  ('grad-aut510-advanced-vehicle-diagnostics',3,'Organize network waveform and operating-data evidence'),
  ('grad-aut510-advanced-vehicle-diagnostics',4,'Generate competing fault hypotheses'),
  ('grad-aut510-advanced-vehicle-diagnostics',5,'Select discriminating tests and measurements'),
  ('grad-aut510-advanced-vehicle-diagnostics',6,'Interpret results with uncertainty and source applicability'),
  ('grad-aut510-advanced-vehicle-diagnostics',7,'Validate the diagnosis against independent evidence'),
  ('grad-aut510-advanced-vehicle-diagnostics',8,'Document the reasoning chain limitations and next step'),
  ('grad-aut600-research-design',1,'Define the research problem and decision context'),
  ('grad-aut600-research-design',2,'Formulate research questions and testable hypotheses'),
  ('grad-aut600-research-design',3,'Select an appropriate experimental or analytical design'),
  ('grad-aut600-research-design',4,'Define variables controls sampling and instrumentation'),
  ('grad-aut600-research-design',5,'Plan data quality uncertainty and analysis methods'),
  ('grad-aut600-research-design',6,'Establish validation and reproducibility criteria'),
  ('grad-aut600-research-design',7,'Integrate ethics provenance limitations and risk controls'),
  ('grad-aut600-research-design',8,'Produce a defensible automotive research proposal'),
  ('grad-aut610-applied-research-project',1,'Confirm the approved applied-research question and scope'),
  ('grad-aut610-applied-research-project',2,'Translate the design into an execution plan'),
  ('grad-aut610-applied-research-project',3,'Collect data under controlled documented conditions'),
  ('grad-aut610-applied-research-project',4,'Quality-check and organize the research evidence'),
  ('grad-aut610-applied-research-project',5,'Analyze results against the research question'),
  ('grad-aut610-applied-research-project',6,'Evaluate uncertainty limitations and competing explanations'),
  ('grad-aut610-applied-research-project',7,'Validate findings and identify unresolved evidence needs'),
  ('grad-aut610-applied-research-project',8,'Produce the final technical research report and presentation'),
  ('grad-aut620-internship',1,'Confirm approved internship objectives and institutional boundaries'),
  ('grad-aut620-internship',2,'Define role responsibilities deliverables and evidence expectations'),
  ('grad-aut620-internship',3,'Document professional safety ethics and communication requirements'),
  ('grad-aut620-internship',4,'Collect non-confidential evidence of advanced technical practice'),
  ('grad-aut620-internship',5,'Relate workplace decisions to graduate automotive concepts'),
  ('grad-aut620-internship',6,'Reflect on uncertainty constraints and professional judgment'),
  ('grad-aut620-internship',7,'Synthesize supervisor feedback and learning evidence'),
  ('grad-aut620-internship',8,'Prepare a governed internship portfolio and reflection'),
  ('grad-aut630-systems-integration',1,'Define the integrated vehicle mission and boundaries'),
  ('grad-aut630-systems-integration',2,'Decompose participating mechanical electrical software and energy domains'),
  ('grad-aut630-systems-integration',3,'Map interfaces dependencies and failure propagation'),
  ('grad-aut630-systems-integration',4,'Trace information energy and control flows'),
  ('grad-aut630-systems-integration',5,'Evaluate integration tradeoffs constraints and risks'),
  ('grad-aut630-systems-integration',6,'Plan interface-level and system-level verification'),
  ('grad-aut630-systems-integration',7,'Interpret integration evidence and unresolved uncertainty'),
  ('grad-aut630-systems-integration',8,'Document a system-level integration and validation rationale'),
  ('grad-aut640-thesis',1,'Confirm thesis scope advisor approval and research boundaries'),
  ('grad-aut640-thesis',2,'Refine the research question and contribution'),
  ('grad-aut640-thesis',3,'Execute the approved research methodology'),
  ('grad-aut640-thesis',4,'Maintain data provenance quality and research records'),
  ('grad-aut640-thesis',5,'Analyze results uncertainty and alternative explanations'),
  ('grad-aut640-thesis',6,'Validate conclusions against objectives and limitations'),
  ('grad-aut640-thesis',7,'Develop the thesis manuscript with traceable evidence'),
  ('grad-aut640-thesis',8,'Prepare and defend the research contribution'),
  ('grad-aut650-capstone',1,'Define the applied automotive problem and stakeholder need'),
  ('grad-aut650-capstone',2,'Translate needs into measurable requirements'),
  ('grad-aut650-capstone',3,'Develop candidate solution concepts and architecture'),
  ('grad-aut650-capstone',4,'Select a defensible design and implementation approach'),
  ('grad-aut650-capstone',5,'Plan testing measurement and validation criteria'),
  ('grad-aut650-capstone',6,'Evaluate performance risks tradeoffs and limitations'),
  ('grad-aut650-capstone',7,'Iterate the solution using test evidence'),
  ('grad-aut650-capstone',8,'Deliver the capstone technical package and presentation'),
  ('grad-aut690-research-seminar',1,'Select a current automotive research topic'),
  ('grad-aut690-research-seminar',2,'Locate and verify authoritative or scholarly sources'),
  ('grad-aut690-research-seminar',3,'Summarize the research question methods and claims'),
  ('grad-aut690-research-seminar',4,'Evaluate evidence quality limitations and uncertainty'),
  ('grad-aut690-research-seminar',5,'Compare competing findings or interpretations'),
  ('grad-aut690-research-seminar',6,'Connect research to automotive technology implications'),
  ('grad-aut690-research-seminar',7,'Prepare an evidence-traceable seminar presentation'),
  ('grad-aut690-research-seminar',8,'Lead scholarly discussion and document follow-up questions');

insert into public.curriculum_reference_mappings (reference_id, lesson_plan_id, role, notes) values
  ('nhtsa-fmvss-135-light-vehicle-brake-systems','ug-aut140-brake-systems','brake-system-regulatory-reference','Governed supporting reference for Automotive Brake Systems. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('technical-writing-for-technicians-2019','ug-aut140-brake-systems','technical-documentation','Governed supporting reference for Automotive Brake Systems. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('automotive-engine-diagnostic-survey-2012','grad-aut510-advanced-vehicle-diagnostics','diagnostic-methods-reference','Governed supporting reference for Advanced Vehicle Diagnostics. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('openstax-principles-data-science-2025','grad-aut510-advanced-vehicle-diagnostics','diagnostic-data-foundation','Governed supporting reference for Advanced Vehicle Diagnostics. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('nist-tn1900-measurement-uncertainty','grad-aut600-research-design','measurement-uncertainty','Governed supporting reference for Automotive Research Design. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('technical-writing-for-technicians-2019','grad-aut600-research-design','research-communication','Governed supporting reference for Automotive Research Design. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('openstax-principles-data-science-2025','grad-aut610-applied-research-project','research-data-foundation','Governed supporting reference for Applied Automotive Research Project. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('technical-writing-for-technicians-2019','grad-aut610-applied-research-project','research-reporting','Governed supporting reference for Applied Automotive Research Project. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('technical-writing-for-technicians-2019','grad-aut620-internship','professional-communication','Governed supporting reference for Graduate Automotive Technology Internship. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('nasa-systems-engineering-handbook-2016','grad-aut620-internship','systems-practice-context','Governed supporting reference for Graduate Automotive Technology Internship. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('nasa-systems-engineering-handbook-2016','grad-aut630-systems-integration','systems-engineering-foundation','Governed supporting reference for Advanced Automotive Systems Integration. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('nist-tn1900-measurement-uncertainty','grad-aut630-systems-integration','verification-uncertainty','Governed supporting reference for Advanced Automotive Systems Integration. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('nist-tn1900-measurement-uncertainty','grad-aut640-thesis','research-uncertainty','Governed supporting reference for Automotive Technology Thesis. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('technical-writing-for-technicians-2019','grad-aut640-thesis','thesis-communication','Governed supporting reference for Automotive Technology Thesis. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('nasa-systems-engineering-handbook-2016','grad-aut650-capstone','systems-engineering-foundation','Governed supporting reference for Applied Automotive Technology Capstone. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('nist-tn1900-measurement-uncertainty','grad-aut650-capstone','test-uncertainty','Governed supporting reference for Applied Automotive Technology Capstone. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('technical-writing-for-technicians-2019','grad-aut690-research-seminar','scholarly-communication','Governed supporting reference for Graduate Research Seminar. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.'),
  ('openstax-principles-data-science-2025','grad-aut690-research-seminar','research-data-literacy','Governed supporting reference for Graduate Research Seminar. Source rights and applicability boundaries remain unchanged; vehicle-specific or institution-specific decisions require applicable authoritative information.')
on conflict (reference_id, lesson_plan_id, role) do update set notes=excluded.notes;

commit;
