begin;

insert into public.curriculum_courses (id, program_id, academic_level, cip_code, title, status) values
  ('aut-501','automotive-engineering-technology','graduate','15.0803','Advanced Automotive Systems','planned'),
  ('aut-515','automotive-engineering-technology','graduate','15.0803','Automotive Systems Modeling','planned'),
  ('aut-520','automotive-engineering-technology','graduate','15.0803','Advanced Vehicle Data Analytics','planned'),
  ('aut-530','automotive-engineering-technology','graduate','15.0803','Advanced Electric Vehicle Systems','planned'),
  ('aut-535','automotive-engineering-technology','graduate','15.0803','Advanced Battery Systems','planned'),
  ('aut-540','automotive-engineering-technology','graduate','15.0803','Power Electronics for Vehicle Systems','planned'),
  ('aut-545','automotive-engineering-technology','graduate','15.0803','Advanced Vehicle Energy Management','planned'),
  ('aut-550','automotive-engineering-technology','graduate','15.0803','Advanced Automotive Networks','planned'),
  ('aut-555','automotive-engineering-technology','graduate','15.0803','Automotive Embedded Systems and ECU Architecture','planned'),
  ('aut-560','automotive-engineering-technology','graduate','15.0803','Advanced ADAS and Vehicle Perception','planned'),
  ('aut-565','automotive-engineering-technology','graduate','15.0803','Autonomous Vehicle Systems','planned'),
  ('aut-570','automotive-engineering-technology','graduate','15.0803','Automotive Cybersecurity Engineering','planned'),
  ('aut-575','automotive-engineering-technology','graduate','15.0803','Software-Defined Vehicle Architecture','planned'),
  ('aut-580','automotive-engineering-technology','graduate','15.0803','Advanced Automotive Control Systems','planned'),
  ('aut-585','automotive-engineering-technology','graduate','15.0803','Vehicle Digital Twins and Simulation','planned'),
  ('aut-590','automotive-engineering-technology','graduate','15.0803','Advanced Automotive Technology Seminar','planned')
on conflict (id) do update set program_id=excluded.program_id, academic_level=excluded.academic_level, cip_code=excluded.cip_code, title=excluded.title, status=excluded.status, updated_at=now();

insert into public.curriculum_competencies (id, course_id, academic_level, competency_area_id, statement, status) values
  ('grad-aut501-integrated-systems','aut-501','graduate',null,'Analyze interactions among advanced automotive system domains, identify interface evidence and uncertainty, and design a traceable system-level verification strategy.','planned'),
  ('grad-aut515-systems-modeling','aut-515','graduate',null,'Construct and evaluate automotive system models, justify parameter choices and assumptions, and assess model validity against appropriate evidence.','planned'),
  ('grad-aut520-data-analytics','aut-520','graduate',null,'Evaluate vehicle datasets using appropriate analytical methods, distinguish statistical patterns from supported technical conclusions, and document uncertainty and validation needs.','planned'),
  ('grad-aut530-advanced-ev-systems','aut-530','graduate',null,'Analyze advanced EV subsystem interactions, evaluate operating evidence across energy-conversion domains, and design a source-supported verification strategy.','planned'),
  ('grad-aut535-battery-systems','aut-535','graduate',null,'Evaluate battery-system models and diagnostic evidence, distinguish estimated states from measured observations, and justify a validation strategy that respects safety and source boundaries.','planned'),
  ('grad-aut540-power-electronics','aut-540','graduate',null,'Analyze vehicle power-electronic energy conversion and control relationships, interpret evidence across electrical and thermal domains, and identify applicable source requirements for validation.','planned'),
  ('grad-aut545-energy-management','aut-545','graduate',null,'Evaluate vehicle energy-flow strategies, articulate optimization objectives and constraints, and justify conclusions using traceable operating evidence.','planned'),
  ('grad-aut550-automotive-networks','aut-550','graduate',null,'Analyze advanced vehicle-network behavior and topology evidence, distinguish communication symptoms from root-cause conclusions, and design a traceable network verification strategy.','planned'),
  ('grad-aut555-embedded-ecu','aut-555','graduate',null,'Evaluate embedded automotive architecture and software/hardware interactions, identify interface evidence and timing constraints conceptually, and design an applicable validation approach.','planned'),
  ('grad-aut560-adas-perception','aut-560','graduate',null,'Evaluate multi-sensor perception evidence, explain sensor-fusion and calibration dependencies, and design a validation strategy that documents environment and configuration limitations.','planned'),
  ('grad-aut565-autonomous-systems','aut-565','graduate',null,'Analyze autonomous-system functional chains, identify cross-domain dependencies and failure evidence, and design a traceable simulation or test validation strategy.','planned'),
  ('grad-aut570-cybersecurity','aut-570','graduate',null,'Evaluate automotive cybersecurity risks and controls using threat-model evidence, distinguish defensive verification from exploit development, and document residual risk and validation needs.','planned'),
  ('grad-aut575-software-defined-vehicle','aut-575','graduate',null,'Evaluate software-defined vehicle architecture tradeoffs, trace software/data dependencies, and design a configuration-aware verification and lifecycle strategy.','planned'),
  ('grad-aut580-control-systems','aut-580','graduate',null,'Evaluate advanced automotive control-system models and evidence, assess stability and estimation assumptions, and justify a validation strategy against system requirements.','planned'),
  ('grad-aut585-digital-twins','aut-585','graduate',null,'Evaluate a vehicle digital-twin architecture, distinguish model state from observed vehicle state, and design calibration and validation activities using traceable data.','planned'),
  ('grad-aut590-technology-seminar','aut-590','graduate',null,'Critically synthesize current automotive research and technical publications, compare competing claims, and communicate evidence-supported conclusions with explicit uncertainty and source provenance.','planned')
on conflict (id) do update set course_id=excluded.course_id, academic_level=excluded.academic_level, competency_area_id=excluded.competency_area_id, statement=excluded.statement, status=excluded.status, updated_at=now();

insert into public.curriculum_lesson_plans (id, course_id, competency_id, academic_level, title, status) values
  ('grad-aut501-integrated-systems','aut-501','grad-aut501-integrated-systems','graduate','Integrated Automotive Systems Analysis','planned'),
  ('grad-aut515-systems-modeling','aut-515','grad-aut515-systems-modeling','graduate','Automotive Systems Modeling, Simulation, and Validation','planned'),
  ('grad-aut520-data-analytics','aut-520','grad-aut520-data-analytics','graduate','Advanced Vehicle Data Analytics and Interpretation','planned'),
  ('grad-aut530-advanced-ev-systems','aut-530','grad-aut530-advanced-ev-systems','graduate','Advanced Electric Vehicle Architecture and Energy Systems','planned'),
  ('grad-aut535-battery-systems','aut-535','grad-aut535-battery-systems','graduate','Advanced Battery Modeling, State Estimation, and Diagnostics','planned'),
  ('grad-aut540-power-electronics','aut-540','grad-aut540-power-electronics','graduate','Vehicle Power Electronics, Conversion, and Control','planned'),
  ('grad-aut545-energy-management','aut-545','grad-aut545-energy-management','graduate','Advanced Vehicle Energy-Flow Analysis and Optimization','planned'),
  ('grad-aut550-automotive-networks','aut-550','grad-aut550-automotive-networks','graduate','Advanced Vehicle Networks, Timing, and Reliability','planned'),
  ('grad-aut555-embedded-ecu','aut-555','grad-aut555-embedded-ecu','graduate','Automotive Embedded Systems and ECU Architecture Analysis','planned'),
  ('grad-aut560-adas-perception','aut-560','grad-aut560-adas-perception','graduate','Advanced ADAS Perception, Sensor Fusion, and Validation','planned'),
  ('grad-aut565-autonomous-systems','aut-565','grad-aut565-autonomous-systems','graduate','Autonomous Vehicle Architecture, Planning, Control, and Validation','planned'),
  ('grad-aut570-cybersecurity','aut-570','grad-aut570-cybersecurity','graduate','Automotive Cybersecurity Threat Modeling and Verification','planned'),
  ('grad-aut575-software-defined-vehicle','aut-575','grad-aut575-software-defined-vehicle','graduate','Software-Defined Vehicle Platforms and Lifecycle Architecture','planned'),
  ('grad-aut580-control-systems','aut-580','grad-aut580-control-systems','graduate','Advanced Automotive Control, Estimation, and Stability','planned'),
  ('grad-aut585-digital-twins','aut-585','grad-aut585-digital-twins','graduate','Vehicle Digital Twins, Simulation, and Predictive Validation','planned'),
  ('grad-aut590-technology-seminar','aut-590','grad-aut590-technology-seminar','graduate','Critical Review of Emerging Automotive Technology','planned')
on conflict (id) do update set course_id=excluded.course_id, competency_id=excluded.competency_id, academic_level=excluded.academic_level, title=excluded.title, status=excluded.status, updated_at=now();

insert into public.curriculum_lesson_steps (lesson_plan_id, position, step_text) values
  ('grad-aut501-integrated-systems',1,'Define the integrated vehicle function'),
  ('grad-aut501-integrated-systems',2,'Map participating domains'),
  ('grad-aut501-integrated-systems',3,'Identify interfaces and dependencies'),
  ('grad-aut501-integrated-systems',4,'Trace energy information and control flow'),
  ('grad-aut501-integrated-systems',5,'Organize available evidence'),
  ('grad-aut501-integrated-systems',6,'Identify uncertainty and missing information'),
  ('grad-aut501-integrated-systems',7,'Design a system-level verification approach'),
  ('grad-aut501-integrated-systems',8,'Document conclusions limitations and next steps'),
  ('grad-aut515-systems-modeling',1,'Define the modeled system and purpose'),
  ('grad-aut515-systems-modeling',2,'Identify variables states and assumptions'),
  ('grad-aut515-systems-modeling',3,'Select a modeling structure'),
  ('grad-aut515-systems-modeling',4,'Establish parameter sources'),
  ('grad-aut515-systems-modeling',5,'Execute or interpret simulation behavior'),
  ('grad-aut515-systems-modeling',6,'Compare model output with evidence'),
  ('grad-aut515-systems-modeling',7,'Evaluate uncertainty and validity'),
  ('grad-aut515-systems-modeling',8,'Document model limitations and next validation work'),
  ('grad-aut520-data-analytics',1,'Define the analytical question'),
  ('grad-aut520-data-analytics',2,'Characterize the dataset and provenance'),
  ('grad-aut520-data-analytics',3,'Prepare variables and time context'),
  ('grad-aut520-data-analytics',4,'Select an analytical approach'),
  ('grad-aut520-data-analytics',5,'Evaluate patterns anomalies or trends'),
  ('grad-aut520-data-analytics',6,'Test alternative interpretations'),
  ('grad-aut520-data-analytics',7,'Plan validation against independent evidence'),
  ('grad-aut520-data-analytics',8,'Document findings uncertainty and limitations'),
  ('grad-aut530-advanced-ev-systems',1,'Define the EV architecture and operating state'),
  ('grad-aut530-advanced-ev-systems',2,'Map energy conversion paths'),
  ('grad-aut530-advanced-ev-systems',3,'Analyze machine and inverter roles'),
  ('grad-aut530-advanced-ev-systems',4,'Connect charging and regenerative functions'),
  ('grad-aut530-advanced-ev-systems',5,'Connect thermal and energy-management functions'),
  ('grad-aut530-advanced-ev-systems',6,'Organize operating evidence'),
  ('grad-aut530-advanced-ev-systems',7,'Design a verification strategy using applicable information'),
  ('grad-aut530-advanced-ev-systems',8,'Document conclusions assumptions and limitations'),
  ('grad-aut535-battery-systems',1,'Define the battery-system question'),
  ('grad-aut535-battery-systems',2,'Separate measured and estimated variables'),
  ('grad-aut535-battery-systems',3,'Select a model or estimation framework'),
  ('grad-aut535-battery-systems',4,'Identify degradation and thermal influences'),
  ('grad-aut535-battery-systems',5,'Evaluate balancing and management logic conceptually'),
  ('grad-aut535-battery-systems',6,'Compare evidence with model expectations'),
  ('grad-aut535-battery-systems',7,'Design a safe validation strategy'),
  ('grad-aut535-battery-systems',8,'Document uncertainty applicability and next steps'),
  ('grad-aut540-power-electronics',1,'Define the conversion function'),
  ('grad-aut540-power-electronics',2,'Map input output and control domains'),
  ('grad-aut540-power-electronics',3,'Identify switching and drive relationships'),
  ('grad-aut540-power-electronics',4,'Trace control behavior conceptually'),
  ('grad-aut540-power-electronics',5,'Evaluate efficiency evidence'),
  ('grad-aut540-power-electronics',6,'Connect thermal behavior and loading'),
  ('grad-aut540-power-electronics',7,'Plan source-supported validation'),
  ('grad-aut540-power-electronics',8,'Document assumptions risks and limitations'),
  ('grad-aut545-energy-management',1,'Define the operating objective'),
  ('grad-aut545-energy-management',2,'Map energy sources sinks and storage'),
  ('grad-aut545-energy-management',3,'Identify controllable energy paths'),
  ('grad-aut545-energy-management',4,'Define constraints and tradeoffs'),
  ('grad-aut545-energy-management',5,'Compare candidate management strategies'),
  ('grad-aut545-energy-management',6,'Evaluate evidence and sensitivity'),
  ('grad-aut545-energy-management',7,'Plan validation across operating conditions'),
  ('grad-aut545-energy-management',8,'Document optimization assumptions and limitations'),
  ('grad-aut550-automotive-networks',1,'Define the communication requirement'),
  ('grad-aut550-automotive-networks',2,'Map the relevant network topology'),
  ('grad-aut550-automotive-networks',3,'Identify protocol and gateway roles'),
  ('grad-aut550-automotive-networks',4,'Analyze timing and message behavior'),
  ('grad-aut550-automotive-networks',5,'Evaluate reliability and fault evidence'),
  ('grad-aut550-automotive-networks',6,'Compare competing network hypotheses'),
  ('grad-aut550-automotive-networks',7,'Design a network verification plan'),
  ('grad-aut550-automotive-networks',8,'Document topology assumptions and limitations'),
  ('grad-aut555-embedded-ecu',1,'Define the ECU function and context'),
  ('grad-aut555-embedded-ecu',2,'Map hardware software and communication layers'),
  ('grad-aut555-embedded-ecu',3,'Identify real-time and interface requirements'),
  ('grad-aut555-embedded-ecu',4,'Trace data and control paths'),
  ('grad-aut555-embedded-ecu',5,'Evaluate available execution evidence'),
  ('grad-aut555-embedded-ecu',6,'Identify version and applicability dependencies'),
  ('grad-aut555-embedded-ecu',7,'Design a validation strategy'),
  ('grad-aut555-embedded-ecu',8,'Document architecture assumptions and limitations'),
  ('grad-aut560-adas-perception',1,'Define the perception task'),
  ('grad-aut560-adas-perception',2,'Map participating sensors and data products'),
  ('grad-aut560-adas-perception',3,'Compare sensing strengths and limitations'),
  ('grad-aut560-adas-perception',4,'Analyze fusion relationships'),
  ('grad-aut560-adas-perception',5,'Identify calibration dependencies'),
  ('grad-aut560-adas-perception',6,'Evaluate scenario and environmental evidence'),
  ('grad-aut560-adas-perception',7,'Design a validation matrix'),
  ('grad-aut560-adas-perception',8,'Document limitations applicability and next tests'),
  ('grad-aut565-autonomous-systems',1,'Define the autonomous function and operating context'),
  ('grad-aut565-autonomous-systems',2,'Map localization mapping and perception inputs'),
  ('grad-aut565-autonomous-systems',3,'Trace planning decisions conceptually'),
  ('grad-aut565-autonomous-systems',4,'Connect planning to vehicle control'),
  ('grad-aut565-autonomous-systems',5,'Identify subsystem dependencies and failure modes'),
  ('grad-aut565-autonomous-systems',6,'Evaluate simulation or test evidence'),
  ('grad-aut565-autonomous-systems',7,'Design a validation strategy across scenarios'),
  ('grad-aut565-autonomous-systems',8,'Document operational limitations and unresolved risks'),
  ('grad-aut570-cybersecurity',1,'Define the protected function and assets'),
  ('grad-aut570-cybersecurity',2,'Map trust boundaries and attack surfaces'),
  ('grad-aut570-cybersecurity',3,'Identify threat scenarios at a defensive level'),
  ('grad-aut570-cybersecurity',4,'Map candidate controls'),
  ('grad-aut570-cybersecurity',5,'Evaluate authentication and network evidence'),
  ('grad-aut570-cybersecurity',6,'Assess detection and diagnostic protections'),
  ('grad-aut570-cybersecurity',7,'Design a defensive verification plan'),
  ('grad-aut570-cybersecurity',8,'Document residual risk assumptions and limitations'),
  ('grad-aut575-software-defined-vehicle',1,'Define the software-defined vehicle function'),
  ('grad-aut575-software-defined-vehicle',2,'Compare zonal and centralized structures'),
  ('grad-aut575-software-defined-vehicle',3,'Map platform and middleware responsibilities'),
  ('grad-aut575-software-defined-vehicle',4,'Trace vehicle data paths'),
  ('grad-aut575-software-defined-vehicle',5,'Analyze update and configuration dependencies'),
  ('grad-aut575-software-defined-vehicle',6,'Evaluate lifecycle and verification evidence'),
  ('grad-aut575-software-defined-vehicle',7,'Design a configuration-aware validation approach'),
  ('grad-aut575-software-defined-vehicle',8,'Document architecture tradeoffs and limitations'),
  ('grad-aut580-control-systems',1,'Define the control objective'),
  ('grad-aut580-control-systems',2,'Establish states inputs outputs and assumptions'),
  ('grad-aut580-control-systems',3,'Analyze feedback structure'),
  ('grad-aut580-control-systems',4,'Evaluate stability conceptually'),
  ('grad-aut580-control-systems',5,'Connect estimation and observation'),
  ('grad-aut580-control-systems',6,'Examine optimization tradeoffs'),
  ('grad-aut580-control-systems',7,'Design simulation or test validation'),
  ('grad-aut580-control-systems',8,'Document model limits and control conclusions'),
  ('grad-aut585-digital-twins',1,'Define the physical and digital system boundary'),
  ('grad-aut585-digital-twins',2,'Identify model components and data interfaces'),
  ('grad-aut585-digital-twins',3,'Establish calibration variables and sources'),
  ('grad-aut585-digital-twins',4,'Connect real-time observations conceptually'),
  ('grad-aut585-digital-twins',5,'Evaluate synchronization and fidelity'),
  ('grad-aut585-digital-twins',6,'Assess predictive outputs and uncertainty'),
  ('grad-aut585-digital-twins',7,'Design calibration and validation tests'),
  ('grad-aut585-digital-twins',8,'Document limitations and update requirements'),
  ('grad-aut590-technology-seminar',1,'Define the seminar question'),
  ('grad-aut590-technology-seminar',2,'Locate relevant scholarly and technical sources'),
  ('grad-aut590-technology-seminar',3,'Evaluate source authority and applicability'),
  ('grad-aut590-technology-seminar',4,'Compare methods evidence and claims'),
  ('grad-aut590-technology-seminar',5,'Identify standards or technical context'),
  ('grad-aut590-technology-seminar',6,'Synthesize competing interpretations'),
  ('grad-aut590-technology-seminar',7,'Present and defend an evidence-based position'),
  ('grad-aut590-technology-seminar',8,'Document provenance limitations and open questions')
on conflict (lesson_plan_id, position) do update set step_text=excluded.step_text;

commit;
