-- TorqueMind external data resource registry
-- Catalogs approved public, government, research, and training data sources.
-- This migration stores metadata only; it does not ingest third-party datasets.

create table if not exists public.external_data_resources (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    organization text,
    category text not null,
    description text,
    homepage_url text,
    api_url text,
    documentation_url text,
    additional_urls jsonb not null default '[]'::jsonb,
    diagnostic_domains text[] not null default '{}',
    access_type text not null default 'public'
        check (access_type in (
            'public',
            'public_api',
            'registration_required',
            'restricted',
            'research_portal'
        )),
    integration_priority integer not null default 3
        check (integration_priority between 1 and 5),
    integration_status text not null default 'planned'
        check (integration_status in (
            'planned',
            'evaluating',
            'approved',
            'integrated',
            'disabled'
        )),
    attribution_required boolean not null default true,
    commercial_use_review_required boolean not null default true,
    is_active boolean not null default true,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists external_data_resources_category_idx
    on public.external_data_resources(category);

create index if not exists external_data_resources_status_idx
    on public.external_data_resources(integration_status);

create index if not exists external_data_resources_priority_idx
    on public.external_data_resources(integration_priority);

create index if not exists external_data_resources_domains_gin_idx
    on public.external_data_resources using gin(diagnostic_domains);

create or replace function public.set_external_data_resource_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists external_data_resources_updated_at
    on public.external_data_resources;

create trigger external_data_resources_updated_at
before update on public.external_data_resources
for each row
execute function public.set_external_data_resource_updated_at();

alter table public.external_data_resources enable row level security;

drop policy if exists "External resources are publicly readable"
    on public.external_data_resources;

create policy "External resources are publicly readable"
on public.external_data_resources
for select
using (is_active = true);

comment on table public.external_data_resources is
'Catalog of external automotive, government, research, environmental, mapping, military, standards, and ML data resources approved for TorqueMind evaluation.';

comment on column public.external_data_resources.integration_priority is
'1 = critical integration, 5 = long-term research opportunity.';

comment on column public.external_data_resources.additional_urls is
'Additional official endpoints, dataset catalogs, or documentation URLs stored as a JSON array.';

insert into public.external_data_resources (
    slug,
    name,
    organization,
    category,
    description,
    homepage_url,
    api_url,
    documentation_url,
    additional_urls,
    diagnostic_domains,
    access_type,
    integration_priority,
    integration_status,
    attribution_required,
    commercial_use_review_required,
    notes
)
values
(
    'nhtsa',
    'National Highway Traffic Safety Administration',
    'U.S. Department of Transportation',
    'automotive-safety',
    'Vehicle identification, VIN decoding, recalls, complaints, investigations, safety ratings, and automotive safety datasets.',
    'https://www.nhtsa.gov/nhtsa-datasets',
    'https://vpic.nhtsa.dot.gov/api/',
    'https://api.nhtsa.gov/',
    '["https://www.nhtsa.gov/nhtsa-datasets"]'::jsonb,
    array['vin','vehicle-profile','recalls','safety','complaints'],
    'public_api',
    1,
    'approved',
    true,
    true,
    'Primary source for VIN decoding and recall enrichment.'
),
(
    'epa-vehicle-data',
    'EPA Vehicle Compliance and Fuel Economy Data',
    'U.S. Environmental Protection Agency',
    'vehicle-specifications',
    'Vehicle emissions certification, compliance, fuel economy, engine, and environmental performance data.',
    'https://www.epa.gov/compliance-and-fuel-economy-data',
    null,
    'https://www.epa.gov/compliance-and-fuel-economy-data',
    '[]'::jsonb,
    array['vehicle-profile','emissions','fuel-economy','engine-specifications'],
    'public',
    1,
    'approved',
    true,
    true,
    'Evaluate dataset licensing and update cadence before automated ingestion.'
),
(
    'fueleconomy-gov',
    'FuelEconomy.gov Web Services',
    'U.S. Department of Energy and EPA',
    'fuel-economy',
    'Fuel economy, vehicle comparison, fuel type, emissions, and efficiency data.',
    'https://www.fueleconomy.gov/',
    'https://www.fueleconomy.gov/ws/',
    'https://www.fueleconomy.gov/ws/',
    '[]'::jsonb,
    array['vehicle-profile','fuel-economy','emissions','operating-cost'],
    'public_api',
    1,
    'approved',
    true,
    true,
    'Useful for vehicle-profile enrichment and efficiency context.'
),
(
    'bureau-transportation-statistics',
    'Bureau of Transportation Statistics',
    'U.S. Department of Transportation',
    'transportation-statistics',
    'National transportation datasets, vehicle usage, freight, infrastructure, and transportation performance.',
    'https://www.bts.gov/',
    null,
    'https://www.bts.gov/',
    '[]'::jsonb,
    array['transportation','fleet-analysis','usage-patterns','research'],
    'public',
    4,
    'planned',
    true,
    true,
    null
),
(
    'data-gov',
    'Data.gov',
    'U.S. General Services Administration',
    'government-data-catalog',
    'Federal open-data catalog for discovering transportation, energy, environmental, geographic, and research datasets.',
    'https://data.gov/',
    null,
    'https://data.gov/',
    '[]'::jsonb,
    array['dataset-discovery','transportation','energy','environment'],
    'public',
    3,
    'evaluating',
    true,
    true,
    'Use as a discovery catalog; validate the originating agency for each dataset.'
),
(
    'noaa',
    'National Oceanic and Atmospheric Administration',
    'NOAA',
    'environmental-data',
    'Weather and environmental data that can be correlated with cold starts, heat, humidity, altitude, and operating conditions.',
    'https://www.noaa.gov/',
    'https://www.weather.gov/documentation/services-web-api',
    'https://www.weather.gov/documentation/services-web-api',
    '[]'::jsonb,
    array['weather','ambient-conditions','diagnostic-context','environment'],
    'public_api',
    2,
    'approved',
    true,
    true,
    'Potential input for environment-aware diagnostic explanations.'
),
(
    'usgs',
    'United States Geological Survey',
    'U.S. Department of the Interior',
    'geospatial-environmental',
    'Elevation, terrain, geographic, environmental, and geospatial data.',
    'https://www.usgs.gov/',
    null,
    'https://www.usgs.gov/',
    '[]'::jsonb,
    array['geospatial','elevation','environment','terrain'],
    'public',
    4,
    'planned',
    true,
    true,
    null
),
(
    'nasa-ntrs',
    'NASA Technical Reports Server',
    'NASA',
    'technical-research',
    'Technical research covering propulsion, materials, sensors, reliability, energy systems, and vehicle-related technologies.',
    'https://ntrs.nasa.gov/',
    null,
    'https://ntrs.nasa.gov/',
    '[]'::jsonb,
    array['reliability-research','materials','sensors','propulsion'],
    'research_portal',
    4,
    'planned',
    true,
    true,
    'Research source; not intended for real-time diagnostic lookup.'
),
(
    'doe',
    'U.S. Department of Energy',
    'U.S. Department of Energy',
    'energy-research',
    'Energy, electric vehicle, battery, alternative fuel, and transportation technology information.',
    'https://www.energy.gov/',
    null,
    'https://www.energy.gov/eere/vehicles',
    '["https://www.energy.gov/eere/vehicles"]'::jsonb,
    array['electric-vehicles','batteries','alternative-fuels','energy'],
    'public',
    2,
    'approved',
    true,
    true,
    null
),
(
    'nrel',
    'National Renewable Energy Laboratory Developer Network',
    'National Renewable Energy Laboratory',
    'energy-api',
    'APIs and datasets for alternative fuels, charging infrastructure, transportation energy, and renewable technologies.',
    'https://www.nrel.gov/',
    'https://developer.nrel.gov/',
    'https://developer.nrel.gov/',
    '[]'::jsonb,
    array['electric-vehicles','charging','alternative-fuels','energy'],
    'registration_required',
    2,
    'evaluating',
    true,
    true,
    'Some APIs may require an API key.'
),
(
    'iihs',
    'Insurance Institute for Highway Safety',
    'Insurance Institute for Highway Safety',
    'vehicle-safety-research',
    'Vehicle crashworthiness, safety ratings, collision avoidance, and loss research.',
    'https://www.iihs.org/',
    null,
    'https://www.iihs.org/',
    '[]'::jsonb,
    array['safety','crashworthiness','vehicle-research'],
    'public',
    3,
    'evaluating',
    true,
    true,
    'Review publication and data-use terms before automated reuse.'
),
(
    'openstreetmap',
    'OpenStreetMap',
    'OpenStreetMap Foundation and contributors',
    'mapping',
    'Open geographic and roadway data for maps, routes, road context, elevation relationships, and location-based diagnostics.',
    'https://www.openstreetmap.org/',
    null,
    'https://wiki.openstreetmap.org/wiki/API',
    '[]'::jsonb,
    array['mapping','road-context','location','routing'],
    'public_api',
    3,
    'evaluating',
    true,
    true,
    'ODbL attribution and share-alike requirements must be reviewed.'
),
(
    'us-census',
    'United States Census Bureau Data',
    'U.S. Census Bureau',
    'demographic-data',
    'Population, community, workforce, education, economic, and geographic datasets.',
    'https://www.census.gov/data.html',
    null,
    'https://www.census.gov/data.html',
    '[]'::jsonb,
    array['demographics','education','market-analysis','geospatial'],
    'public',
    5,
    'planned',
    true,
    true,
    null
),
(
    'logsa',
    'Logistics Support Activity',
    'U.S. Army',
    'military-maintenance',
    'Army logistics, maintenance, readiness, parts, and technical support systems.',
    'https://www.logsa.army.mil',
    null,
    'https://www.logsa.army.mil',
    '[]'::jsonb,
    array['military-maintenance','logistics','readiness','technical-data'],
    'restricted',
    3,
    'evaluating',
    true,
    true,
    'Access and redistribution may be restricted. Do not ingest controlled or export-restricted content.'
),
(
    'army-publishing-directorate',
    'Army Publishing Directorate',
    'U.S. Army',
    'military-publications',
    'Official Army publications, regulations, technical manuals, pamphlets, and forms.',
    'https://armypubs.army.mil/',
    null,
    'https://armypubs.army.mil/',
    '[]'::jsonb,
    array['military-maintenance','technical-manuals','training','safety'],
    'public',
    3,
    'evaluating',
    true,
    true,
    'Verify distribution restrictions for each publication.'
),
(
    'dtic',
    'Defense Technical Information Center',
    'U.S. Department of Defense',
    'defense-research',
    'Defense research reports covering vehicle reliability, maintenance, systems engineering, sensors, and logistics.',
    'https://discover.dtic.mil/',
    null,
    'https://discover.dtic.mil/',
    '[]'::jsonb,
    array['reliability-research','military-maintenance','systems-engineering'],
    'research_portal',
    4,
    'planned',
    true,
    true,
    'Use only publicly releasable and appropriately marked material.'
),
(
    'naval-postgraduate-school',
    'Naval Postgraduate School',
    'U.S. Department of the Navy',
    'academic-research',
    'Academic research on logistics, maintenance, autonomy, energy, systems engineering, and defense technology.',
    'https://nps.edu/',
    null,
    'https://nps.edu/',
    '[]'::jsonb,
    array['research','logistics','systems-engineering','maintenance'],
    'research_portal',
    5,
    'planned',
    true,
    true,
    null
),
(
    'afrl',
    'Air Force Research Laboratory',
    'U.S. Air Force',
    'defense-research',
    'Research in propulsion, materials, autonomy, sensors, energy, and advanced vehicle technologies.',
    'https://afresearchlab.com/',
    null,
    'https://afresearchlab.com/',
    '[]'::jsonb,
    array['research','propulsion','materials','sensors','reliability'],
    'research_portal',
    5,
    'planned',
    true,
    true,
    null
),
(
    'nist',
    'National Institute of Standards and Technology',
    'U.S. Department of Commerce',
    'standards',
    'Standards, cybersecurity guidance, measurements, testing methodologies, AI risk management, and technical reference material.',
    'https://www.nist.gov/',
    null,
    'https://www.nist.gov/',
    '[]'::jsonb,
    array['standards','cybersecurity','measurement','testing','ai-governance'],
    'public',
    2,
    'approved',
    true,
    true,
    null
),
(
    'uci-machine-learning',
    'UCI Machine Learning Repository',
    'University of California, Irvine',
    'machine-learning-data',
    'Public datasets for machine-learning experimentation, benchmarking, and model evaluation.',
    'https://archive.ics.uci.edu/',
    null,
    'https://archive.ics.uci.edu/',
    '[]'::jsonb,
    array['machine-learning','model-evaluation','research'],
    'public',
    4,
    'evaluating',
    true,
    true,
    'Dataset-specific licenses must be reviewed.'
),
(
    'kaggle',
    'Kaggle',
    'Google LLC',
    'machine-learning-data',
    'Community datasets, notebooks, competitions, and machine-learning experimentation resources.',
    'https://www.kaggle.com/',
    null,
    'https://www.kaggle.com/docs/api',
    '[]'::jsonb,
    array['machine-learning','dataset-discovery','model-evaluation'],
    'registration_required',
    5,
    'evaluating',
    true,
    true,
    'Each dataset may have separate licensing and commercial-use restrictions.'
)
on conflict (slug) do update set
    name = excluded.name,
    organization = excluded.organization,
    category = excluded.category,
    description = excluded.description,
    homepage_url = excluded.homepage_url,
    api_url = excluded.api_url,
    documentation_url = excluded.documentation_url,
    additional_urls = excluded.additional_urls,
    diagnostic_domains = excluded.diagnostic_domains,
    access_type = excluded.access_type,
    integration_priority = excluded.integration_priority,
    attribution_required = excluded.attribution_required,
    commercial_use_review_required = excluded.commercial_use_review_required,
    notes = excluded.notes,
    updated_at = now();

create table if not exists public.diagnostic_data_domains (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    description text,
    processing_order integer not null default 100,
    created_at timestamptz not null default now()
);

create table if not exists public.external_resource_domain_links (
    resource_id bigint not null
        references public.external_data_resources(id)
        on delete cascade,
    domain_id bigint not null
        references public.diagnostic_data_domains(id)
        on delete cascade,
    usage_role text not null default 'reference'
        check (usage_role in (
            'primary',
            'enrichment',
            'reference',
            'research',
            'validation'
        )),
    primary key (resource_id, domain_id)
);

alter table public.diagnostic_data_domains enable row level security;
alter table public.external_resource_domain_links enable row level security;

drop policy if exists "Diagnostic domains are publicly readable"
    on public.diagnostic_data_domains;

create policy "Diagnostic domains are publicly readable"
on public.diagnostic_data_domains
for select
using (true);

drop policy if exists "Resource domain links are publicly readable"
    on public.external_resource_domain_links;

create policy "Resource domain links are publicly readable"
on public.external_resource_domain_links
for select
using (true);

insert into public.diagnostic_data_domains (
    slug,
    name,
    description,
    processing_order
)
values
    (
        'user-symptoms',
        'User Symptoms',
        'Student or technician observations, complaints, and operating conditions.',
        10
    ),
    (
        'vehicle-profile',
        'Vehicle Profile',
        'VIN, model, engine, fuel type, emissions family, recalls, and specifications.',
        20
    ),
    (
        'repair-knowledge',
        'Repair Knowledge',
        'Diagnostic procedures, technical publications, standards, research, and repair context.',
        30
    ),
    (
        'live-obd-data',
        'Live OBD Data',
        'Diagnostic trouble codes, freeze-frame data, PIDs, sensor readings, and network information.',
        40
    ),
    (
        'environmental-context',
        'Environmental Context',
        'Weather, altitude, geography, temperature, humidity, and road conditions.',
        50
    ),
    (
        'reliability-research',
        'Reliability Research',
        'Public research related to failure modes, materials, reliability, and systems engineering.',
        60
    ),
    (
        'explainable-report',
        'Explainable Diagnostic Report',
        'Evidence-based diagnostic conclusion, confidence, sources, safety considerations, and recommended next steps.',
        100
    )
on conflict (slug) do update set
    name = excluded.name,
    description = excluded.description,
    processing_order = excluded.processing_order;

insert into public.external_resource_domain_links (
    resource_id,
    domain_id,
    usage_role
)
select r.id, d.id, mapping.usage_role
from (
    values
        ('nhtsa', 'vehicle-profile', 'primary'),
        ('nhtsa', 'repair-knowledge', 'enrichment'),
        ('epa-vehicle-data', 'vehicle-profile', 'primary'),
        ('fueleconomy-gov', 'vehicle-profile', 'enrichment'),
        ('noaa', 'environmental-context', 'primary'),
        ('usgs', 'environmental-context', 'enrichment'),
        ('openstreetmap', 'environmental-context', 'enrichment'),
        ('doe', 'repair-knowledge', 'reference'),
        ('nrel', 'repair-knowledge', 'reference'),
        ('nist', 'repair-knowledge', 'validation'),
        ('nasa-ntrs', 'reliability-research', 'research'),
        ('dtic', 'reliability-research', 'research'),
        ('logsa', 'repair-knowledge', 'reference'),
        ('army-publishing-directorate', 'repair-knowledge', 'reference'),
        ('uci-machine-learning', 'reliability-research', 'research'),
        ('kaggle', 'reliability-research', 'research')
) as mapping(resource_slug, domain_slug, usage_role)
join public.external_data_resources r
    on r.slug = mapping.resource_slug
join public.diagnostic_data_domains d
    on d.slug = mapping.domain_slug
on conflict (resource_id, domain_id) do update set
    usage_role = excluded.usage_role;
